In [3]:
import numpy as np
import pandas as pd 

cars_per_cap = [809, 731, 588, 18, 200, 70, 45]
country = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
drives_right = [True, False, False, False, True, True, True]
data = {"cars_per_cap":cars_per_cap,"country":country,"drives_right":drives_right} 
data

{'cars_per_cap': [809, 731, 588, 18, 200, 70, 45],
 'country': ['United States',
  'Australia',
  'Japan',
  'India',
  'Russia',
  'Morocco',
  'Egypt'],
 'drives_right': [True, False, False, False, True, True, True]}

In [5]:
cars = pd.DataFrame(data)
cars

   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

In [6]:
type(cars)

pandas.core.frame.DataFrame

In [11]:
cars = pd.read_csv("cars.csv", header = None) 
cars

       0    1              2      3      4
0   USCA   US  United States  809.0  False
1  ASPAC  AUS      Australia  731.0   True
2  ASPAC  JAP          Japan  588.0   True
3  ASPAC   IN          India   18.0   True
4  ASPAC   RU         Russia  200.0  False
5  LATAM  MOR        Morocco   70.0  False
6    AFR   EG          Egypt   45.0  False
7    EUR  ENG        England    NaN   True

In [12]:
cars.columns

Int64Index([0, 1, 2, 3, 4], dtype='int64')

In [13]:
cars.columns = ["country code", "region","country","cars_per_cap","drive_right"]
cars

  country code region        country  cars_per_cap  drive_right
0         USCA     US  United States         809.0        False
1        ASPAC    AUS      Australia         731.0         True
2        ASPAC    JAP          Japan         588.0         True
3        ASPAC     IN          India          18.0         True
4        ASPAC     RU         Russia         200.0        False
5        LATAM    MOR        Morocco          70.0        False
6          AFR     EG          Egypt          45.0        False
7          EUR    ENG        England           NaN         True

In [16]:
cars_df = pd.read_csv("cars.csv",header = None, index_col = 0)
cars_df.columns = ["region", "country","cars_per_cap","drive_right"]
cars_df

      region        country  cars_per_cap  drive_right
0
USCA      US  United States         809.0        False
ASPAC    AUS      Australia         731.0         True
ASPAC    JAP          Japan         588.0         True
ASPAC     IN          India          18.0         True
ASPAC     RU         Russia         200.0        False
LATAM    MOR        Morocco          70.0        False
AFR       EG          Egypt          45.0        False
EUR      ENG        England           NaN         True

In [23]:
cars_df.index

Index(['USCA', 'ASPAC', 'ASPAC', 'ASPAC', 'ASPAC', 'LATAM', 'AFR', 'EUR'], dtype='object', name=0)

In [24]:
cars_df.index.name = None 
cars_df

      region        country  cars_per_cap  drive_right
USCA      US  United States         809.0        False
ASPAC    AUS      Australia         731.0         True
ASPAC    JAP          Japan         588.0         True
ASPAC     IN          India          18.0         True
ASPAC     RU         Russia         200.0        False
LATAM    MOR        Morocco          70.0        False
AFR       EG          Egypt          45.0        False
EUR      ENG        England           NaN         True

In [25]:
cars_df.index.name = "country_code"
cars_df

             region        country  cars_per_cap  drive_right
country_code
USCA             US  United States         809.0        False
ASPAC           AUS      Australia         731.0         True
ASPAC           JAP          Japan         588.0         True
ASPAC            IN          India          18.0         True
ASPAC            RU         Russia         200.0        False
LATAM           MOR        Morocco          70.0        False
AFR              EG          Egypt          45.0        False
EUR             ENG        England           NaN         True

In [32]:
cars_df = pd.read_csv("cars.csv", header = None) 
cars_df.columns = ["country_code", "region", "country","cars_per_cap","drives_right"]
cars_df.set_index(["region", "country_code"], inplace = True) 
cars_df

                           country  cars_per_cap  drives_right
region country_code
US     USCA          United States         809.0         False
AUS    ASPAC             Australia         731.0          True
JAP    ASPAC                 Japan         588.0          True
IN     ASPAC                 India          18.0          True
RU     ASPAC                Russia         200.0         False
MOR    LATAM               Morocco          70.0         False
EG     AFR                   Egypt          45.0         False
ENG    EUR                 England           NaN          True

In [34]:
import pandas as pd 
rating_df = pd.read_csv("rating.csv")
rating_df.head()

      ID Department     Office  Rating
0  U2F26    Finance  New Delhi     3.4
1  U2M61  Marketing  New Delhi     3.9
2  U1S15      Sales  New Delhi     2.8
3  U1H87         HR     Mumbai     2.1
4  U1S51      Sales  New Delhi     4.6

In [38]:
rating_df["Rating"]<3.5

0       True
1      False
2       True
3       True
4      False
       ...
528    False
529     True
530     True
531     True
532     True
Name: Rating, Length: 533, dtype: bool

In [40]:
rating_df["Training"] = rating_df.Rating.apply(lambda x: "Yes" if x<3.5 else "No")
rating_df

        ID Department     Office  Rating Training
0    U2F26    Finance  New Delhi     3.4      Yes
1    U2M61  Marketing  New Delhi     3.9       No
2    U1S15      Sales  New Delhi     2.8      Yes
3    U1H87         HR     Mumbai     2.1      Yes
4    U1S51      Sales  New Delhi     4.6       No
..     ...        ...        ...     ...      ...
528  U3S44      Sales  New Delhi     4.8       No
529  U2M11  Marketing  Bangalore     2.5      Yes
530  U3F53    Finance  Bangalore     3.2      Yes
531  U3S46      Sales  Bangalore     2.9      Yes
532  U3S28      Sales  New Delhi     2.9      Yes

[533 rows x 5 columns]

In [47]:
for i in ['Finance', 'HR', 'Sales', 'Marketing']:
    print(i, len(rating_df[(rating_df['Training'] == 'No') & (rating_df['Department'] == i)]) / len(rating_df[rating_df['Department'] == i]) * 100)

Finance 50.74626865671642
HR 61.06870229007634
Sales 53.07692307692308
Marketing 51.449275362318836

In [43]:
for i in ["Finance","HR", "Sales","Marketing"]: 
    print(i,len(rating_df[(rating_df["Training"]=="No") & (rating_df["Department"] == i)]) / len(rating_df[rating_df["Department"]==i])*100

SyntaxError: unexpected EOF while parsing (2315308861.py, line 3)