In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
sales = pd.read_excel("sales.xlsx")
sales

          Market             Region  No_of_Orders    Profit      Sales
0         Africa     Western Africa           251 -12901.51   78476.06
1         Africa    Southern Africa            85  11768.58   51319.50
2         Africa       North Africa           182  21643.08   86698.89
3         Africa     Eastern Africa           110   8013.04   44182.60
4         Africa     Central Africa           103  15606.30   61689.99
5   Asia Pacific       Western Asia           382 -16766.90  124312.24
6   Asia Pacific      Southern Asia           469  67998.76  351806.60
7   Asia Pacific  Southeastern Asia           533  20948.84  329751.38
8   Asia Pacific            Oceania           646  54734.02  408002.98
9   Asia Pacific       Eastern Asia           414  72805.10  315390.77
10  Asia Pacific       Central Asia            37  -2649.76    8190.74
11        Europe     Western Europe           964  82091.27  656637.14
12        Europe    Southern Europe           338  18911.49  215703.93
13        Europe    Northern Europe           367  43237.44  252969.09
14        Europe     Eastern Europe           241  25050.69  108258.93
15         LATAM      South America           496  12377.59  210710.49
16         LATAM    Central America           930  74679.54  461670.28
17         LATAM          Caribbean           288  13529.59  116333.05
18          USCA         Western US           490  44303.65  251991.83
19          USCA        Southern US           255  19991.83  148771.91
20          USCA         Eastern US           443  47462.04  264973.98
21          USCA         Central US           356  33697.43  170416.31
22          USCA             Canada            49   7246.62   26298.81

In [7]:
sales = pd.read_excel("sales.xlsx",index_col = [0,1])
sales

                                No_of_Orders    Profit      Sales
Market       Region
Africa       Western Africa              251 -12901.51   78476.06
             Southern Africa              85  11768.58   51319.50
             North Africa                182  21643.08   86698.89
             Eastern Africa              110   8013.04   44182.60
             Central Africa              103  15606.30   61689.99
Asia Pacific Western Asia                382 -16766.90  124312.24
             Southern Asia               469  67998.76  351806.60
             Southeastern Asia           533  20948.84  329751.38
             Oceania                     646  54734.02  408002.98
             Eastern Asia                414  72805.10  315390.77
             Central Asia                 37  -2649.76    8190.74
Europe       Western Europe              964  82091.27  656637.14
             Southern Europe             338  18911.49  215703.93
             Northern Europe             367  43237.44  252969.09
             Eastern Europe              241  25050.69  108258.93
LATAM        South America               496  12377.59  210710.49
             Central America             930  74679.54  461670.28
             Caribbean                   288  13529.59  116333.05
USCA         Western US                  490  44303.65  251991.83
             Southern US                 255  19991.83  148771.91
             Eastern US                  443  47462.04  264973.98
             Central US                  356  33697.43  170416.31
             Canada                       49   7246.62   26298.81

In [9]:
sales.head(3)

                        No_of_Orders    Profit     Sales
Market Region
Africa Western Africa            251 -12901.51  78476.06
       Southern Africa            85  11768.58  51319.50
       North Africa              182  21643.08  86698.89

In [10]:
sales.tail()

                    No_of_Orders    Profit      Sales
Market Region
USCA   Western US            490  44303.65  251991.83
       Southern US           255  19991.83  148771.91
       Eastern US            443  47462.04  264973.98
       Central US            356  33697.43  170416.31
       Canada                 49   7246.62   26298.81

In [11]:
 sales.info

<bound method DataFrame.info of                                 No_of_Orders    Profit      Sales
Market       Region
Africa       Western Africa              251 -12901.51   78476.06
             Southern Africa              85  11768.58   51319.50
             North Africa                182  21643.08   86698.89
             Eastern Africa              110   8013.04   44182.60
             Central Africa              103  15606.30   61689.99
Asia Pacific Western Asia                382 -16766.90  124312.24
             Southern Asia               469  67998.76  351806.60
             Southeastern Asia           533  20948.84  329751.38
             Oceania                     646  54734.02  408002.98
             Eastern Asia                414  72805.10  315390.77
             Central Asia                 37  -2649.76    8190.74
Europe       Western Europe              964  82091.27  656637.14
             Southern Europe             338  18911.49  215703.93
             Northern Europe             367  43237.44  252969.09
             Eastern Europe              241  25050.69  108258.93
LATAM        South America               496  12377.59  210710.49
             Central America             930  74679.54  461670.28
             Caribbean                   288  13529.59  116333.05
USCA         Western US                  490  44303.65  251991.83
             Southern US                 255  19991.83  148771.91
             Eastern US                  443  47462.04  264973.98
             Central US                  356  33697.43  170416.31
             Canada                       49   7246.62   26298.81>

In [13]:
sales.describe()

       No_of_Orders        Profit          Sales
count     23.000000     23.000000      23.000000
mean     366.478261  28859.944783  206285.108696
std      246.590361  27701.193773  160589.886606
min       37.000000 -16766.900000    8190.740000
25%      211.500000  12073.085000   82587.475000
50%      356.000000  20948.840000  170416.310000
75%      479.500000  45882.845000  290182.375000
max      964.000000  82091.270000  656637.140000

In [15]:
sales["Profit"]

Market        Region
Africa        Western Africa      -12901.51
              Southern Africa      11768.58
              North Africa         21643.08
              Eastern Africa        8013.04
              Central Africa       15606.30
Asia Pacific  Western Asia        -16766.90
              Southern Asia        67998.76
              Southeastern Asia    20948.84
              Oceania              54734.02
              Eastern Asia         72805.10
              Central Asia         -2649.76
Europe        Western Europe       82091.27
              Southern Europe      18911.49
              Northern Europe      43237.44
              Eastern Europe       25050.69
LATAM         South America        12377.59
              Central America      74679.54
              Caribbean            13529.59
USCA          Western US           44303.65
              Southern US          19991.83
              Eastern US           47462.04
              Central US           33697.43
              Canada                7246.62
Name: Profit, dtype: float64

In [16]:
sales = pd.read_excel("sales.xlsx",index_col = [1])
sales

                         Market  No_of_Orders    Profit      Sales
Region
Western Africa           Africa           251 -12901.51   78476.06
Southern Africa          Africa            85  11768.58   51319.50
North Africa             Africa           182  21643.08   86698.89
Eastern Africa           Africa           110   8013.04   44182.60
Central Africa           Africa           103  15606.30   61689.99
Western Asia       Asia Pacific           382 -16766.90  124312.24
Southern Asia      Asia Pacific           469  67998.76  351806.60
Southeastern Asia  Asia Pacific           533  20948.84  329751.38
Oceania            Asia Pacific           646  54734.02  408002.98
Eastern Asia       Asia Pacific           414  72805.10  315390.77
Central Asia       Asia Pacific            37  -2649.76    8190.74
Western Europe           Europe           964  82091.27  656637.14
Southern Europe          Europe           338  18911.49  215703.93
Northern Europe          Europe           367  43237.44  252969.09
Eastern Europe           Europe           241  25050.69  108258.93
South America             LATAM           496  12377.59  210710.49
Central America           LATAM           930  74679.54  461670.28
Caribbean                 LATAM           288  13529.59  116333.05
Western US                 USCA           490  44303.65  251991.83
Southern US                USCA           255  19991.83  148771.91
Eastern US                 USCA           443  47462.04  264973.98
Central US                 USCA           356  33697.43  170416.31
Canada                     USCA            49   7246.62   26298.81

# display sales columns

In [19]:
sales.Sales

Region
Western Africa        78476.06
Southern Africa       51319.50
North Africa          86698.89
Eastern Africa        44182.60
Central Africa        61689.99
Western Asia         124312.24
Southern Asia        351806.60
Southeastern Asia    329751.38
Oceania              408002.98
Eastern Asia         315390.77
Central Asia           8190.74
Western Europe       656637.14
Southern Europe      215703.93
Northern Europe      252969.09
Eastern Europe       108258.93
South America        210710.49
Central America      461670.28
Caribbean            116333.05
Western US           251991.83
Southern US          148771.91
Eastern US           264973.98
Central US           170416.31
Canada                26298.81
Name: Sales, dtype: float64

In [20]:
sales.Sales

Region
Western Africa        78476.06
Southern Africa       51319.50
North Africa          86698.89
Eastern Africa        44182.60
Central Africa        61689.99
Western Asia         124312.24
Southern Asia        351806.60
Southeastern Asia    329751.38
Oceania              408002.98
Eastern Asia         315390.77
Central Asia           8190.74
Western Europe       656637.14
Southern Europe      215703.93
Northern Europe      252969.09
Eastern Europe       108258.93
South America        210710.49
Central America      461670.28
Caribbean            116333.05
Western US           251991.83
Southern US          148771.91
Eastern US           264973.98
Central US           170416.31
Canada                26298.81
Name: Sales, dtype: float64

In [21]:
type(sales["Sales"])

pandas.core.series.Series

In [22]:
sales.dtypes

Market           object
No_of_Orders      int64
Profit          float64
Sales           float64
dtype: object

In [31]:
sales.iloc[(5)]

Market          Asia Pacific
No_of_Orders             382
Profit              -16766.9
Sales              124312.24
Name: Western Asia, dtype: object

In [32]:
import pandas as pd
forestfile_df = pd.read_csv("forestfires.csv")
forestfile_df

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [34]:
df_2 = forestfile_df[["month","day","temp","wind"]]
df_2

    month  day  temp  wind
0     mar  fri   8.2   6.7
1     oct  tue  18.0   0.9
2     oct  sat  14.6   1.3
3     mar  fri   8.3   4.0
4     mar  sun  11.4   1.8
..    ...  ...   ...   ...
512   aug  sun  27.8   2.7
513   aug  sun  21.9   5.8
514   aug  sun  21.2   6.7
515   aug  sat  25.6   4.0
516   nov  tue  11.8   4.5

[517 rows x 4 columns]

In [35]:
sales

                         Market  No_of_Orders    Profit      Sales
Region
Western Africa           Africa           251 -12901.51   78476.06
Southern Africa          Africa            85  11768.58   51319.50
North Africa             Africa           182  21643.08   86698.89
Eastern Africa           Africa           110   8013.04   44182.60
Central Africa           Africa           103  15606.30   61689.99
Western Asia       Asia Pacific           382 -16766.90  124312.24
Southern Asia      Asia Pacific           469  67998.76  351806.60
Southeastern Asia  Asia Pacific           533  20948.84  329751.38
Oceania            Asia Pacific           646  54734.02  408002.98
Eastern Asia       Asia Pacific           414  72805.10  315390.77
Central Asia       Asia Pacific            37  -2649.76    8190.74
Western Europe           Europe           964  82091.27  656637.14
Southern Europe          Europe           338  18911.49  215703.93
Northern Europe          Europe           367  43237.44  252969.09
Eastern Europe           Europe           241  25050.69  108258.93
South America             LATAM           496  12377.59  210710.49
Central America           LATAM           930  74679.54  461670.28
Caribbean                 LATAM           288  13529.59  116333.05
Western US                 USCA           490  44303.65  251991.83
Southern US                USCA           255  19991.83  148771.91
Eastern US                 USCA           443  47462.04  264973.98
Central US                 USCA           356  33697.43  170416.31
Canada                     USCA            49   7246.62   26298.81

In [37]:
sales_profit_df = sales[["sales", "profit"]]
sales_profit_df

KeyError: "None of [Index(['sales', 'profit'], dtype='object')] are in the [columns]"

In [38]:
sales

                         Market  No_of_Orders    Profit      Sales
Region
Western Africa           Africa           251 -12901.51   78476.06
Southern Africa          Africa            85  11768.58   51319.50
North Africa             Africa           182  21643.08   86698.89
Eastern Africa           Africa           110   8013.04   44182.60
Central Africa           Africa           103  15606.30   61689.99
Western Asia       Asia Pacific           382 -16766.90  124312.24
Southern Asia      Asia Pacific           469  67998.76  351806.60
Southeastern Asia  Asia Pacific           533  20948.84  329751.38
Oceania            Asia Pacific           646  54734.02  408002.98
Eastern Asia       Asia Pacific           414  72805.10  315390.77
Central Asia       Asia Pacific            37  -2649.76    8190.74
Western Europe           Europe           964  82091.27  656637.14
Southern Europe          Europe           338  18911.49  215703.93
Northern Europe          Europe           367  43237.44  252969.09
Eastern Europe           Europe           241  25050.69  108258.93
South America             LATAM           496  12377.59  210710.49
Central America           LATAM           930  74679.54  461670.28
Caribbean                 LATAM           288  13529.59  116333.05
Western US                 USCA           490  44303.65  251991.83
Southern US                USCA           255  19991.83  148771.91
Eastern US                 USCA           443  47462.04  264973.98
Central US                 USCA           356  33697.43  170416.31
Canada                     USCA            49   7246.62   26298.81

In [43]:
sales[["Market", "Profit","Sales"]].head(3)

                 Market    Profit     Sales
Region
Western Africa   Africa -12901.51  78476.06
Southern Africa  Africa  11768.58  51319.50
North Africa     Africa  21643.08  86698.89

In [44]:
sales.loc["Southern Asia"]

Market          Asia Pacific
No_of_Orders             469
Profit              67998.76
Sales               351806.6
Name: Southern Asia, dtype: object

In [46]:
sales.loc["Southern Asia", "Sales"]

351806.6

In [47]:
sales.iloc[6]

Market          Asia Pacific
No_of_Orders             469
Profit              67998.76
Sales               351806.6
Name: Southern Asia, dtype: object

In [50]:
sales.loc[:,["Market","Sales","Profit"]].head(5)

                 Market     Sales    Profit
Region
Western Africa   Africa  78476.06 -12901.51
Southern Africa  Africa  51319.50  11768.58
North Africa     Africa  86698.89  21643.08
Eastern Africa   Africa  44182.60   8013.04
Central Africa   Africa  61689.99  15606.30

In [51]:
sales.iloc[:,[0,3,2]].head(5)

                 Market     Sales    Profit
Region
Western Africa   Africa  78476.06 -12901.51
Southern Africa  Africa  51319.50  11768.58
North Africa     Africa  86698.89  21643.08
Eastern Africa   Africa  44182.60   8013.04
Central Africa   Africa  61689.99  15606.30

In [52]:
#display data for western africa Southern Africa, North Africa

In [53]:
sales.loc[["Western Africa","Southern Africa","North Africa"],:]

                 Market  No_of_Orders    Profit     Sales
Region
Western Africa   Africa           251 -12901.51  78476.06
Southern Africa  Africa            85  11768.58  51319.50
North Africa     Africa           182  21643.08  86698.89

In [57]:
sales.loc[["Western Africa","Southern Africa","North Africa"], ["Sales","Profit"] ]

                    Sales    Profit
Region
Western Africa   78476.06 -12901.51
Southern Africa  51319.50  11768.58
North Africa     86698.89  21643.08

In [55]:
sales.iloc[0:3,2:4]

                   Profit     Sales
Region
Western Africa  -12901.51  78476.06
Southern Africa  11768.58  51319.50
North Africa     21643.08  86698.89

# Filtring the Data

In [61]:
#display the LATAM and European countries with Sales >30000
sales[sales(["Market"].isin(["LATM","Europe"])) & (sales["Sales"]>250000)]

AttributeError: 'list' object has no attribute 'isin'

In [63]:
import pandas as pd
data = pd.read_csv("weatherdata.csv", header = 0)
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0
...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0

In [64]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [65]:
data.tail()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0

In [66]:
data.info

<bound method DataFrame.info of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN
1       2008-12-02   Albury      7.4     25.1       0.0          NaN
2       2008-12-03   Albury     12.9     25.7       0.0          NaN
3       2008-12-04   Albury      9.2     28.0       0.0          NaN
4       2008-12-05   Albury     17.5     32.3       1.0          NaN
...            ...      ...      ...      ...       ...          ...
142188  2017-06-20    Uluru      3.5     21.8       0.0          NaN
142189  2017-06-21    Uluru      2.8     23.4       0.0          NaN
142190  2017-06-22    Uluru      3.6     25.3       0.0          NaN
142191  2017-06-23    Uluru      5.4     26.9       0.0          NaN
142192  2017-06-24    Uluru      7.8     27.0       0.0          NaN

        Sunshine WindGustDir  WindGustSpeed
0            NaN           W           44.0
1            NaN         WNW           44.0
2            NaN         WSW           46.0
3            NaN          NE           24.0
4            NaN           W           41.0
...          ...         ...            ...
142188       NaN           E           31.0
142189       NaN           E           31.0
142190       NaN         NNW           22.0
142191       NaN           N           37.0
142192       NaN          SE           28.0

[142193 rows x 9 columns]>

In [67]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132923.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,39.984292
std,6.403283,7.117618,8.465173,4.188537,3.781525,13.588801
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,31.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,48.000000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000

In [68]:
data["Sunshine"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
142188   NaN
142189   NaN
142190   NaN
142191   NaN
142192   NaN
Name: Sunshine, Length: 142193, dtype: float64

In [69]:
data["Sunshine"]>4

0         False
1         False
2         False
3         False
4         False
          ...
142188    False
142189    False
142190    False
142191    False
142192    False
Name: Sunshine, Length: 142193, dtype: bool

In [72]:
data[data["Sunshine"]> 4]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5940,2009-01-02,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0
5941,2009-01-03,Cobar,15.5,34.1,0.0,12.6,13.3,SE,30.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
...,...,...,...,...,...,...,...,...,...
139108,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [ ]:
#Note High sunshine corresponidng to low rainfall 
#Example 1.2 Filtering dataframes

In [73]:
data[(data["Sunshine"]>5) & (data["MaxTemp"]>35)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
5944,2009-01-06,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0
5948,2009-01-10,Cobar,19.0,35.5,0.0,12.0,12.3,ENE,48.0
...,...,...,...,...,...,...,...,...,...
138862,2016-10-17,Darwin,25.1,35.2,0.0,7.4,11.5,NNE,39.0
138879,2016-11-03,Darwin,24.4,35.5,0.0,7.8,9.9,NW,35.0
138892,2016-11-16,Darwin,25.7,35.2,0.0,5.4,11.3,NW,26.0
138905,2016-11-29,Darwin,25.8,35.1,0.8,4.8,6.4,SSE,46.0
138910,2016-12-04,Darwin,25.8,35.2,0.0,NaN,12.0,ESE,33.0

In [74]:
pd.DatetimeIndex(data["Date"]).year

Int64Index([2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008, 2008,
            ...
            2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017, 2017],
           dtype='int64', name='Date', length=142193)

In [76]:
pd.DatetimeIndex(data["Date"])

DatetimeIndex(['2008-12-01', '2008-12-02', '2008-12-03', '2008-12-04',
               '2008-12-05', '2008-12-06', '2008-12-07', '2008-12-08',
               '2008-12-09', '2008-12-10',
               ...
               '2017-06-15', '2017-06-16', '2017-06-17', '2017-06-18',
               '2017-06-19', '2017-06-20', '2017-06-21', '2017-06-22',
               '2017-06-23', '2017-06-24'],
              dtype='datetime64[ns]', name='Date', length=142193, freq=None)

In [80]:
data["Year"] = pd.DatetimeIndex(data["Date"]).year
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008

In [87]:
data["Month"] = pd.DatetimeIndex(data["Date"]).month
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12
...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,2017,6
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,2017,6
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,2017,6
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,2017,6
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,2017,6

In [88]:
data.set_index("Month")
data

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12
...,...,...,...,...,...,...,...,...,...,...,...
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0,2017,6
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,2017,6
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,2017,6
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,2017,6
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,2017,6

In [92]:
data["Days_of_month"] = pd.DatetimeIndex(data["Date"]).day
data.head(5)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Days_of_month
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,2008,12,4
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,2008,12,5

In [ ]:
#temp given in celcius into ferhenhieght with new cloumn

In [94]:
data["Maxtemp_F"] = data["MaxTemp"] * 9/5 + 35 
data.head(3)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Days_of_month,Maxtemp_F
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1,76.22
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2,80.18
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3,81.26

In [96]:
data["Month"] = pd.DatetimeIndex(data["Date"]).month
data.head(3)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,Year,Month,Days_of_month,Maxtemp_F,Month_new
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,2008,12,1,76.22,12
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2008,12,2,80.18,12
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,2008,12,3,81.26,12

In [153]:
data_rainy_notrainy = data["Rainfall"].apply(lambda x: "Rainy" if x>50 else "Not Rainy")
data_rainy_notrainy.head()

0    Not Rainy
1    Not Rainy
2    Not Rainy
3    Not Rainy
4    Not Rainy
Name: Rainfall, dtype: object

In [154]:
#data["Is_Raining"] = data["Rainfall"].apply(lambda x: "Rainy" if x>50 else "Not Rainy")
data.head(3)

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0

In [163]:
data_rainy_notrainy = data["Is_raining"] = data.Rainfall.apply(lambda x: "Rainy" if x>50 else "Not Rainy")
data_rainy_notrainy

0    Not Rainy
1    Not Rainy
2    Not Rainy
3    Not Rainy
4    Not Rainy
Name: Rainfall, dtype: object

In [174]:
data = pd.read_csv("weatherdata.csv")
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [175]:
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [176]:
data.tail()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
142188,2017-06-20,Uluru,3.5,21.8,0.0,NaN,NaN,E,31.0
142189,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0
142190,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0
142191,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0
142192,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0

In [177]:
data_bylocation = data.groupby(by = ["Location"]).mean()
data_bylocation.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed
Location,,,,,,
Adelaide,12.628368,22.945402,1.572185,5.824924,7.752002,36.530812
Albany,12.948461,20.072587,2.255073,4.207273,6.658765,NaN
Albury,9.520899,22.630963,1.925710,NaN,NaN,32.953016
AliceSprings,13.125182,29.244191,0.869355,9.029929,9.581944,40.533714
BadgerysCreek,11.136900,24.023111,2.207925,NaN,NaN,33.609890

In [178]:
data_bylocation.sort_values("Rainfall", ascending = False).head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed
Location,,,,,,
Cairns,21.199197,29.544344,5.765317,6.211976,7.575995,38.067991
Darwin,23.210530,32.540977,5.094048,6.319089,8.499310,40.582355
CoffsHarbour,14.365774,23.915575,5.054592,3.904267,7.362374,39.232197
GoldCoast,17.341490,25.752971,3.728933,NaN,NaN,42.472539
Wollongong,14.949058,21.476510,3.589127,NaN,NaN,45.695257