## 1.1 Pandas Revision
<hr/>

In [2]:
import pandas as pd

In [3]:
nba = pd.read_csv('nba.csv')

In [4]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

### Selecting Columns
<hr/>

In [5]:
mycols =['Name','College']

nba[mycols].head()

            Name            College
0  Avery Bradley              Texas
1    Jae Crowder          Marquette
2   John Holland  Boston University
3    R.J. Hunter      Georgia State
4  Jonas Jerebko                NaN

## Filtering Records
<hr/>

Find Players playing from Texas College

In [53]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.00
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.00
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4842684.11
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.00
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.00

In [56]:
c1 =  nba.Position == 'SG'
c2 = nba.College == 'Kentucky'

newdf = nba[c1 & c2]

In [57]:
newdf

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
125,Archie Goodwin,Phoenix Suns,20.0,SG,21.0,6-5,200.0,Kentucky,1160160.0
193,Jodie Meeks,Detroit Pistons,20.0,SG,28.0,6-4,210.0,Kentucky,6270000.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0

In [58]:
newdf.Team.value_counts()

Phoenix Suns         2
Charlotte Hornets    1
Boston Celtics       1
Detroit Pistons      1
Name: Team, dtype: int64

In [6]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [7]:
texasPlayers = nba.College == 'Texas'
nba[texasPlayers]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
289,Jordan Hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0

## Handling Mulitple Conditions
<hr/>

Find Players from 'Texas' College Playing for 'PG' Position

In [9]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [10]:
c1 = nba.College == 'Texas'

c2 = nba.Position == 'PG'

nba[ c1 & c2 ]      # here & means AND

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000.0

In [ ]:
### Quick Activity : Find Players whose Age is 22 and Weigh More then 235 Pounds.

In [11]:
c1= nba.Age==22
c2=nba.Weight> 235
nba[c1 &c2]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
49,Joel Embiid,Philadelphia 76ers,21.0,C,22.0,7-0,250.0,Kansas,4626960.0
51,Richaun Holmes,Philadelphia 76ers,22.0,PF,22.0,6-10,245.0,Bowling Green,1074169.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
246,Clint Capela,Houston Rockets,15.0,PF,22.0,6-10,240.0,NaN,1242720.0
250,Montrezl Harrell,Houston Rockets,35.0,PF,22.0,6-8,240.0,Louisville,1000000.0
268,Jarell Martin,Memphis Grizzlies,10.0,PF,22.0,6-10,239.0,LSU,1230840.0
412,Steven Adams,Oklahoma City Thunder,12.0,C,22.0,7-0,255.0,Pittsburgh,2279040.0

## 1.2 Dealing with NaN in Pandas
<hr/>

In [13]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
there are 2 Methods to Handle NaN in Pandas

1. Delete Rows Containing NaN using dropNa()

2. replace NaN using fillNa()

In [ ]:
nba.dropna(how='all',inplace=True)

In [ ]:
any : any means Delete ROw if any of the column contains NaN
    
all : all means Delete a ROW only if ALL Columns Contain NaN

In [ ]:
source dataframe i.e nba remains uneffected or still contains NaN

In [ ]:
newdf = nba.dropna(how='all')

In [ ]:
nba = nba.dropna(how='all')

In [ ]:
nba.dropna(how='all',inplace=True)

In [16]:
nba.shape

(458, 9)

In [17]:
nba.dropna(how='all',inplace=True)

In [18]:
nba.shape

(457, 9)

In [19]:
nba.dropna(how='any',inplace=True)

In [20]:
nba.shape

(364, 9)

In [21]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 364 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      364 non-null    object
 1   Team      364 non-null    object
 2   Number    364 non-null    float64
 3   Position  364 non-null    object
 4   Age       364 non-null    float64
 5   Height    364 non-null    object
 6   Weight    364 non-null    float64
 7   College   364 non-null    object
 8   Salary    364 non-null    float64
dtypes: float64(4), object(5)
memory usage: 28.4+ KB

In [22]:
nba.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [23]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0

2. replace NaN using fillNa()

In [24]:
nba = pd.read_csv('nba.csv')

In [25]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

Objective: to replace NaN in Salary Column with Average of Salary.

In [27]:
round(nba.Salary.mean(),2)

4842684.11

In [28]:
nba.Salary.fillna( round(nba.Salary.mean(),2)     ,  inplace=True    )

In [30]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.00
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.00
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4842684.11
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.00
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.00

Quick Activity : replace NaN in College Column with 'other'

## 1.3  DataType Conversion in Pandas
<hr/>

In [31]:
df = pd.read_csv('employees.csv')

In [32]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [33]:
df.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [34]:
df['Start Date']= pd.to_datetime(df['Start Date'])

In [35]:
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [36]:
df['Last Login Time']= pd.to_datetime(df['Last Login Time'])

In [37]:
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time      datetime64[ns]
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [38]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-29 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2023-01-29 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2023-01-29 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-29 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-29 16:47:00,101004,1.389,True,Client Services

In [39]:
df['Senior Management'] =df['Senior Management'].astype('bool')

In [40]:
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time      datetime64[ns]
Salary                        int64
Bonus %                     float64
Senior Management              bool
Team                         object
dtype: object

In [ ]:
.astype() : its a datatype conversion , can be used for converting to int/float/bool/Object.

## 1.4 Analytical Functions in Pandas
<hr/>

In [41]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-29 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2023-01-29 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2023-01-29 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-29 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-29 16:47:00,101004,1.389,True,Client Services

Find the count of distinct/unique values in 'Gender' Column !

In [42]:
df.Gender.nunique()

2

How many Teams are their in Data ?

In [43]:
df.Team.nunique()

10

Find the Distinct/Unique Values in Gender !

In [44]:
df.Gender.unique()

array(['Male', 'Female', nan], dtype=object)

In [ ]:
df.Gender.uni

What are the Names of Team Present in Data ?

In [45]:
df.Team.unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

How many Males & Females are Their ?

value_counts() : this function returns the total repetition count(frequency) of each
    unique value across all rows.

In [46]:
df.Gender.value_counts()

Female    431
Male      424
Name: Gender, dtype: int64

How many Employees are Working in Each Team ???

In [47]:
df.Team.value_counts()

Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: Team, dtype: int64

How many Males and Females are Working in Finance Team ???

In [49]:
finEmp= df.Team == 'Finance'

finTeam = df[finEmp]

finTeam.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,2023-01-29 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-29 13:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,2023-01-29 10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,2023-01-29 07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,2023-01-29 22:47:00,114796,6.796,False,Finance

In [52]:
finTeam.Gender.value_counts()

Female    44
Male      41
Name: Gender, dtype: int64

who is the most paid employee from Marketing Team working for Senior Management?
find the name of employee.

## 1.5 Working with Indexes in Pandas
<hr/>

In [59]:
bond = pd.read_csv('jamesbond.csv')

In [60]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

## Access Rows using Row Indexes
<hr/>

In [61]:
bond.iloc[2]

Film                   Goldfinger
Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: 2, dtype: object

In [62]:
bond.iloc[[2,5,7]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [63]:
bond.iloc[:3]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [64]:
bond.iloc[23:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

Imagine how easy it would be if we could search rows using Film Titles

In [65]:
bond.head(3)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [66]:
bond.set_index('Film',inplace=True)

In [67]:
bond.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [ ]:
when we are using index other then Row Index use .loc

In [68]:
bond.loc['Goldfinger']

bond.iloc[2]

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [70]:
bond.reset_index(inplace=True)

In [71]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [ ]:
follow the instructions

1. set the Year Column as index using set_index()
2. using .loc find the movies produced in the year 1985

3. share the movie name in chat section.

4. reset the index

In [76]:
bond.set_index('Year',inplace=True)

In [77]:
bond.loc[1985]['Film']

'A View to a Kill'

In [78]:
bond.reset_index(inplace=True)

## 1.6 Grouping in Pandas
<hr/>

In [81]:
fortune = pd.read_csv('fortune1000.csv',index_col='Rank')

In [82]:
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [83]:
secGrp = fortune.groupby('Sector')

In [ ]:
# POINT TO NOTE

There are 21 Groups(DataFrames) inside secGrp Object.

Each Group is Named After Sector Name

you can fetch each group using get_group(<sectorName>)

In [85]:
secGrp.get_group('Health Care')['Profits'].sum()

106114

In [87]:
secGrp.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

In [ ]:
# .agg()

{'column':'operation'}

In [90]:
secGrp.agg({'Revenue':'sum','Profits':['sum','mean'],'Employees':['max','min','sum','mean']})

                              Revenue Profits              Employees        \
                                  sum     sum         mean       max   min
Sector
Aerospace & Defense            357940   28742  1437.100000    197200  6955
Apparel                         95968    8236   549.066667     65300  5978
Business Services              272195   28227   553.470588    216500  2400
Chemicals                      243897   22628   754.266667     52000  1979
Energy                        1517809  -73447  -602.024590     75600   480
Engineering & Construction     153983    5304   204.000000     92000  1036
Financials                    2217159  260209  1872.007194    331000   187
Food and Drug Stores           483769   16759  1117.266667    431000  1616
Food, Beverages & Tobacco      555967   51417  1195.744186    263000  1857
Health Care                   1614707  106114  1414.853333    203500  2924
Hotels, Resturants & Leisure   169546   20697   827.880000    505000  8500
Household Products             234737   14428   515.285714    110000  4406
Industrials                    497581   20764   451.391304    333000  4104
Materials                      259145    4428   102.976744     60000    52
Media                          220764   24347   973.880000    185000  2341
Motor Vehicles & Parts         482540   25898  1079.083333    215000  2700
Retailing                     1465076   47830   597.875000   2300000  2155
Technology                    1377600  180473  1769.343137    411798  2285
Telecommunications             461834   48637  3242.466667    281450  2700
Transportation                 408508   44169  1226.916667    341240  1223
Wholesalers                    444800    8233   205.825000     78500   500


                                  sum          mean
Sector
Aerospace & Defense            968057  48402.850000
Apparel                        346397  23093.133333
Business Services             1361050  26687.254902
Chemicals                      463651  15455.033333
Energy                        1188927   9745.303279
Engineering & Construction     406708  15642.615385
Financials                    3359948  24172.287770
Food and Drug Stores          1395398  93026.533333
Food, Beverages & Tobacco     1211632  28177.488372
Health Care                   2678289  35710.520000
Hotels, Resturants & Leisure  2484245  99369.800000
Household Products             646038  23072.785714
Industrials                   1545229  33591.934783
Materials                      638123  14840.069767
Media                          550314  22012.560000
Motor Vehicles & Parts        1082560  45106.666667
Retailing                     6227629  77845.362500
Technology                    3578949  35087.735294
Telecommunications             832468  55497.866667
Transportation                1536793  42688.694444
Wholesalers                    525597  13139.925000