In [7]:
import numpy as np

Let us Convert a Python list into Nd Array

In [8]:
sampleData =[10,20,30,40,50]

np.array()  # converts the list into Nd Array

In [9]:
myarr = np.array(sampleData)

In [10]:
type(myarr)

numpy.ndarray

In [11]:
print(sampleData)
print(myarr)

[10, 20, 30, 40, 50]
[10 20 30 40 50]

In [ ]:
sampleData.

In [ ]:
myarr.

In [ ]:
Let us Talk about the Ease of Processing Data Factor.

In [14]:
sampleData + 1

TypeError: can only concatenate list (not "int") to list

In [13]:
myarr + 1

array([11, 21, 31, 41, 51])

In [ ]:
Let us talk about the High Performance Factor.

In [ ]:
# Memory Consumption Test, Python vs numpy.

In [ ]:
Objective: to find out how much memory is occupied by 1 integer in python vs numpy

In [15]:
# python test

import sys
print(sys.getsizeof(5),' bytes')

28  bytes

In [16]:
# numpy test

import numpy as np

print(np.array([1,2,3]).itemsize,' bytes')

8  bytes

In [ ]:
# Speed Test

In [ ]:
# objective: to add 1 million numbers using python vs numpy
# one taking less time will be the winner.

import numpy as np
import time

SIZE = 1000000

A1  = range(SIZE)
A2  = range(SIZE)

L1  = np.arange(SIZE)
L2  = np.arange(SIZE)


start = time.time()
result =[x+y for x,y in zip(A1,A2)]
stop = time.time()

print('Python took ',(stop-start) * 1000, ' ms')

start = time.time()
result = L1+L2
stop = time.time()

print('Numpy took ',(stop-start) * 1000, ' ms')

### Creating ND Arrays
<hr/>

In [17]:
## Creating 1D Array

a=[1,2,3,4,5]

a_arr = np.array(a)

a_arr

array([1, 2, 3, 4, 5])

In [18]:
a_arr.ndim

1

In [19]:
## Creating 2D Array : Group of 1D Array Forms 2D Array

b=[
    [1,2,3],
    [4,5,6]
  ]

b_arr = np.array(b)
b_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b_arr.ndim

2

In [21]:
b_arr[0,1]

2

In [ ]:
## Creating 3D Array : Group of 2D Array Forms 3D Array

In [22]:
c=[

    [
        [1,2,3],
        [4,5,6]
    ]

    ,

    [
        [7,8,9],
        [10,11,12]
    ]

]

c_arr = np.array(c)
c_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
c_arr.ndim

3

In [24]:
c_arr[0,1,0]

4

### Slicing
<hr/>

In [25]:
b=[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
]

b_arr = np.array(b)

In [26]:
b_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
Row Index Targeted : 2 and 3 (in slicing 2 :        OR      2:4)
    
Col Index Targeted : 0,1 and 2 (in slicing :3       OR      0:3)

In [29]:
b_arr[2:, :3]

array([[11, 12, 13],
       [16, 17, 18]])

In [30]:
b_arr[1:3,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [ ]:
Row Index Targeted : 2
Col Index Targted  : ALL 
    
Syntax:  arr [row,col]
    
b_arr[ 2 , : ]

In [28]:
b_arr[ 2 , : ]

array([11, 12, 13, 14, 15])

In [ ]:
Row Index Targeted : ALL  (in slicing : )
    
Col Index Targeted : 3

In [27]:
b_arr [ : , 3 ]

array([ 4,  9, 14, 19])

In [31]:
b_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
print('Sum ',b_arr.sum())
print('Max ',b_arr.max())
print('Min ',b_arr.min())

Sum  210
Max  20
Min  1

In [36]:
print('Colum wise Total ',b_arr.sum(axis=0))

Colum wise Total  [34 38 42 46 50]

In [37]:
print('Row wise Total ',b_arr.sum(axis=1))

Row wise Total  [15 40 65 90]

In [ ]:
Post Tea Break
Pandas

Pandas
<hr/>

In [ ]:
What is Pandas ?

Pandas is a python library primarily used for Data Analysis.

In [ ]:
Pandas is Built on Top of Numpy : it means that pandas uses Numpy ND Array Internally
    to store the Data.

In [ ]:
How does pandas differs from Numpy ? 


Pandas Provides Analytical Functions that numpy doesn't have.

In [ ]:
How does Pandas Provides Access to Its Functionalities ?

Pandas Provides its own Data Structures
    to 
    
    Store Data
    Manipulate Data
    &
    Analyse Data
    
those ARE :
    
            - Series
            - DataFrame

In [ ]:
Series : it is used to store,manipulate & analyse 1D or linear Data eg. list 
    
DataFrame : it is used to store,manipulate & analyse 2D or Tabular Data eg. like excel data.

## Working with Series Data
<hr/>

In [48]:
import pandas as pd

let us convert a Python list into series

pd.Series() # this function help us convert list to Series

In [49]:
ice_cream =['vanilla','rum-raisin','chocolate','strawberry']

In [50]:
myseries = pd.Series(ice_cream)

In [51]:
type(myseries)

pandas.core.series.Series

In [52]:
myseries

0       vanilla
1    rum-raisin
2     chocolate
3    strawberry
dtype: object

In [53]:
myseries[2]

'chocolate'

## Working with DataFrame
<hr/>

In [54]:
import pandas as pd

pd.read_csv() # this function reads the content of File and returns DataFrame.

In [55]:
nba = pd.read_csv('nba.csv')

In [56]:
type(nba)

pandas.core.frame.DataFrame

In [57]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Inspection
<hr/>

In [58]:
# how many rows and cols are there

nba.shape

(458, 9)

In [59]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [60]:
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [61]:
# for detailed summary

nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [62]:
# head()

nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [63]:
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [66]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [67]:
# how many missing values are there in each column.

nba.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [70]:
nba.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [71]:
# .iloc

nba.iloc[2]

Name             John Holland
Team           Boston Celtics
Number                   30.0
Position                   SG
Age                      27.0
Height                    6-5
Weight                  205.0
College     Boston University
Salary                    NaN
Name: 2, dtype: object

In [72]:
nba.iloc[[2,5,7]]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0

In [73]:
nba.iloc[:4]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

### Accessing a Single Column
<hr/>

In [74]:
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [77]:
nba.Name.head(3)

0    Avery Bradley
1      Jae Crowder
2     John Holland
Name: Name, dtype: object

In [78]:
nba['Name']

0    Avery Bradley
1      Jae Crowder
2     John Holland
Name: Name, dtype: object

In [ ]:
# difference in (dot) and [square Bracket]

let us assume we have a column 'my college'

nba.my college   ❌ Error
nba['my column'] ✅ Success

In [79]:
nba[['Name','College']].head()

            Name            College
0  Avery Bradley              Texas
1    Jae Crowder          Marquette
2   John Holland  Boston University
3    R.J. Hunter      Georgia State
4  Jonas Jerebko                NaN