In [5]:
import pandas as pd
sales_df = pd.read_excel("sales.xlsx")
new_sales_df = sales_df["Region"]
new_sales_df

0        Western Africa
1       Southern Africa
2          North Africa
3        Eastern Africa
4        Central Africa
5          Western Asia
6         Southern Asia
7     Southeastern Asia
8               Oceania
9          Eastern Asia
10         Central Asia
11       Western Europe
12      Southern Europe
13      Northern Europe
14       Eastern Europe
15        South America
16      Central America
17            Caribbean
18           Western US
19          Southern US
20           Eastern US
21           Central US
22               Canada
Name: Region, dtype: object

In [19]:
import pandas as pd 
forestfires_2 = pd.read_csv("forestfires.csv")
forestfires_2.head()

   X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [23]:
forestfires_2[["month","day","temp","rain","area"]]
forestfires_2

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
1    7  4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0   0.00
2    7  4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0   0.00
3    8  6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2   0.00
4    8  6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
512  4  3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

[517 rows x 13 columns]

In [29]:
sales_df = pd.read_excel("sales.xlsx")
sales_df[["Sales"]]

        Sales
0    78476.06
1    51319.50
2    86698.89
3    44182.60
4    61689.99
5   124312.24
6   351806.60
7   329751.38
8   408002.98
9   315390.77
10    8190.74
11  656637.14
12  215703.93
13  252969.09
14  108258.93
15  210710.49
16  461670.28
17  116333.05
18  251991.83
19  148771.91
20  264973.98
21  170416.31
22   26298.81

In [32]:
sales_df.head()

   Market           Region  No_of_Orders    Profit     Sales
0  Africa   Western Africa           251 -12901.51  78476.06
1  Africa  Southern Africa            85  11768.58  51319.50
2  Africa     North Africa           182  21643.08  86698.89
3  Africa   Eastern Africa           110   8013.04  44182.60
4  Africa   Central Africa           103  15606.30  61689.99

In [35]:
sales_df.loc[0:2,["Profit","Sales"]].head()

     Profit     Sales
0 -12901.51  78476.06
1  11768.58  51319.50
2  21643.08  86698.89

In [56]:
sales_df.iloc[0:10, [1,4]]

              Region      Sales
0     Western Africa   78476.06
1    Southern Africa   51319.50
2       North Africa   86698.89
3     Eastern Africa   44182.60
4     Central Africa   61689.99
5       Western Asia  124312.24
6      Southern Asia  351806.60
7  Southeastern Asia  329751.38
8            Oceania  408002.98
9       Eastern Asia  315390.77

In [64]:
forest_df = pd.read_csv("forestfires.csv")
forest_df.set_index(["month", "rain"])

            X  Y  day  FFMC    DMC     DC   ISI  temp  RH  wind   area
month rain
mar   0.0   7  5  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.00
oct   0.0   7  4  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.00
      0.0   7  4  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.00
mar   0.2   8  6  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.00
      0.0   8  6  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.00
...        .. ..  ...   ...    ...    ...   ...   ...  ..   ...    ...
aug   0.0   4  3  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   6.44
      0.0   2  4  sun  81.6   56.7  665.6   1.9  21.9  71   5.8  54.29
      0.0   7  4  sun  81.6   56.7  665.6   1.9  21.2  70   6.7  11.16
      0.0   1  4  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.00
nov   0.0   6  3  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.00

[517 rows x 11 columns]

In [2]:
print("Hello world")

Hello world

In [3]:
def sqrt(x):
    return x ** 0.5
print(sqrt(4))

2.0

In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt