In [4]:
import pandas as pd
sales = pd.read_csv("junesales.csv", header = 0)
sales.head()

       Date  Tea_sales(in 100's)
0  6/1/2011                   26
1  6/2/2011                   35
2  6/3/2011                   37
3  6/4/2011                   33
4  6/5/2011                   25

In [17]:
sales["daysofmonth"] = pd.DatetimeIndex(sales["Date"]).day
sales.head()

       Date  Tea_sales(in 100's)  salesofmonth  daysofmonth
0  6/1/2011                   26             1            1
1  6/2/2011                   35             2            2
2  6/3/2011                   37             3            3
3  6/4/2011                   33             4            4
4  6/5/2011                   25             5            5

In [9]:
data = pd.read_csv("weatherdata.csv",header = 0)
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [14]:
data["daysofmonth"] = pd.DatetimeIndex(data["Date"]).day
data["Year"] = pd.DatetimeIndex(data["Date"]).year
data["Month"] = pd.DatetimeIndex(data["Date"]).month
data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,daysofmonth,Year,Month
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,1,2008,12
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2,2008,12
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,3,2008,12
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,4,2008,12
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,5,2008,12

In [15]:
Newcastle_data = data[(data["Location"]== "Newcastle") & (data["Year"] ==2011) & (data["Month"]== 6)]
Newcastle_data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,daysofmonth,Year,Month
15605,2011-06-01,Newcastle,NaN,21.2,6.0,NaN,NaN,NaN,NaN,1,2011,6
15606,2011-06-02,Newcastle,NaN,20.2,4.0,NaN,NaN,NaN,NaN,2,2011,6
15607,2011-06-03,Newcastle,10.7,20.2,0.4,NaN,NaN,NaN,NaN,3,2011,6
15608,2011-06-04,Newcastle,9.4,20.4,0.0,NaN,NaN,NaN,NaN,4,2011,6
15609,2011-06-05,Newcastle,9.6,18.8,3.0,NaN,NaN,NaN,NaN,5,2011,6

In [19]:
merge_data = Newcastle_data.merge(sales, on = "daysofmonth")
merge_data.head()

,Date_x,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,daysofmonth,Year,Month,Date_y,Tea_sales(in 100's),salesofmonth
0,2011-06-01,Newcastle,NaN,21.2,6.0,NaN,NaN,NaN,NaN,1,2011,6,6/1/2011,26,1
1,2011-06-02,Newcastle,NaN,20.2,4.0,NaN,NaN,NaN,NaN,2,2011,6,6/2/2011,35,2
2,2011-06-03,Newcastle,10.7,20.2,0.4,NaN,NaN,NaN,NaN,3,2011,6,6/3/2011,37,3
3,2011-06-04,Newcastle,9.4,20.4,0.0,NaN,NaN,NaN,NaN,4,2011,6,6/4/2011,33,4
4,2011-06-05,Newcastle,9.6,18.8,3.0,NaN,NaN,NaN,NaN,5,2011,6,6/5/2011,25,5

In [20]:
 data["Location"].unique()

array(['Albury', 'BadgerysCreek', 'Cobar', 'CoffsHarbour', 'Moree',
       'Newcastle', 'NorahHead', 'NorfolkIsland', 'Penrith', 'Richmond',
       'Sydney', 'SydneyAirport', 'WaggaWagga', 'Williamtown',
       'Wollongong', 'Canberra', 'Tuggeranong', 'MountGinini', 'Ballarat',
       'Bendigo', 'Sale', 'MelbourneAirport', 'Melbourne', 'Mildura',
       'Nhil', 'Portland', 'Watsonia', 'Dartmoor', 'Brisbane', 'Cairns',
       'GoldCoast', 'Townsville', 'Adelaide', 'MountGambier', 'Nuriootpa',
       'Woomera', 'Albany', 'Witchcliffe', 'PearceRAAF', 'PerthAirport',
       'Perth', 'SalmonGums', 'Walpole', 'Hobart', 'Launceston',
       'AliceSprings', 'Darwin', 'Katherine', 'Uluru'], dtype=object)

In [25]:
state = pd.read_csv("locationsandstates.csv",header =0)
state.head()

         Location             State
0          Sydney  New South Wales
1          Albury  New South Wales
2        Armidale  New South Wales
3        Bathurst  New South Wales
4  Blue Mountains  New South Wales

In [26]:
state_data= data.merge(state, on= "Location",how= "left") 
state_data.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,daysofmonth,Year,Month,State
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,1,2008,12,New South Wales
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,2,2008,12,New South Wales
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,3,2008,12,New South Wales
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,4,2008,12,New South Wales
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,5,2008,12,New South Wales

In [27]:
state_data.shape

(142193, 13)