In [2]:

cars_per_cap = [809, 731, 588, 18, 200, 70, 45]
country = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
drives_right = [True, False, False, False, True, True, True]
import pandas as pd 
data = {"cars_per_cap": cars_per_cap, "country": country, "drives_right": drives_right}
data

{'cars_per_cap': [809, 731, 588, 18, 200, 70, 45],
 'country': ['United States',
  'Australia',
  'Japan',
  'India',
  'Russia',
  'Morocco',
  'Egypt'],
 'drives_right': [True, False, False, False, True, True, True]}

In [4]:
cars = pd.DataFrame(data)
cars

   cars_per_cap        country  drives_right
0           809  United States          True
1           731      Australia         False
2           588          Japan         False
3            18          India         False
4           200         Russia          True
5            70        Morocco          True
6            45          Egypt          True

In [5]:
type(cars)

pandas.core.frame.DataFrame

In [21]:
import pandas as pd 
cars_df = pd.read_csv("cars.csv")
cars_df

    USCA   US United States    809  FALSE
0  ASPAC  AUS     Australia  731.0   True
1  ASPAC  JAP         Japan  588.0   True
2  ASPAC   IN         India   18.0   True
3  ASPAC   RU        Russia  200.0  False
4  LATAM  MOR       Morocco   70.0  False
5    AFR   EG         Egypt   45.0  False
6    EUR  ENG       England    NaN   True

In [22]:
cars_df = pd.read_csv("cars.csv",header = None)
cars_df

       0    1              2      3      4
0   USCA   US  United States  809.0  False
1  ASPAC  AUS      Australia  731.0   True
2  ASPAC  JAP          Japan  588.0   True
3  ASPAC   IN          India   18.0   True
4  ASPAC   RU         Russia  200.0  False
5  LATAM  MOR        Morocco   70.0  False
6    AFR   EG          Egypt   45.0  False
7    EUR  ENG        England    NaN   True

In [31]:
cars_df.columns = ["Country code", "region", "country", "cars_per_cap", "dirve_right"]
cars_df.set_index(['region"'])

SyntaxError: invalid syntax (1470876964.py, line 2)

In [32]:
cars_df = pd.read_csv("cars.csv", header = None)
cars_df.columns = ["reqion", "country", "cars_per_cap", "drive_right"]
cars_df

ValueError: Length mismatch: Expected axis has 5 elements, new values have 4 elements

In [19]:
cars.index.name = "country_code"
cars

             Country code region        country  cars_per_cap  dirve_right
country_code
0                    USCA     US  United States         809.0        False
1                   ASPAC    AUS      Australia         731.0         True
2                   ASPAC    JAP          Japan         588.0         True
3                   ASPAC     IN          India          18.0         True
4                   ASPAC     RU         Russia         200.0        False
5                   LATAM    MOR        Morocco          70.0        False
6                     AFR     EG          Egypt          45.0        False
7                     EUR    ENG        England           NaN         True

In [28]:
cars_df.index.name = "country_code"
cars_df

             reqion        country  cars_per_cap  drive_right
country_code
USCA             US  United States         809.0        False
ASPAC           AUS      Australia         731.0         True
ASPAC           JAP          Japan         588.0         True
ASPAC            IN          India          18.0         True
ASPAC            RU         Russia         200.0        False
LATAM           MOR        Morocco          70.0        False
AFR              EG          Egypt          45.0        False
EUR             ENG        England           NaN         True

In [30]:
cars_df = pd.read_csv("cars.csv",header = None)
cars_df.coloums = ['country_code',"region","country","cars_per_cap","drives_right"]
cars_df.set_index(["region", "country_code"], inplace = True) 
cars_df

/var/folders/9m/ztkm5bns0x1b521x6wdpd4640000gn/T/ipykernel_73505/1343647009.py:2: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  cars_df.coloums = ['country_code',"region","country","cars_per_cap","drives_right"]

KeyError: "None of ['region', 'country_code'] are in the columns"

In [33]:
cars_df = pd.read_csv("cars.csv")
cars_df

    USCA   US United States    809  FALSE
0  ASPAC  AUS     Australia  731.0   True
1  ASPAC  JAP         Japan  588.0   True
2  ASPAC   IN         India   18.0   True
3  ASPAC   RU        Russia  200.0  False
4  LATAM  MOR       Morocco   70.0  False
5    AFR   EG         Egypt   45.0  False
6    EUR  ENG       England    NaN   True

In [34]:
cars_df.columns = ["contry_code", "Region", "country","cars_per_caps","drive_right"]
cars_df

  contry_code Region    country  cars_per_caps  drive_right
0       ASPAC    AUS  Australia          731.0         True
1       ASPAC    JAP      Japan          588.0         True
2       ASPAC     IN      India           18.0         True
3       ASPAC     RU     Russia          200.0        False
4       LATAM    MOR    Morocco           70.0        False
5         AFR     EG      Egypt           45.0        False
6         EUR    ENG    England            NaN         True

In [39]:
cars_df = pd.read_csv("cars.csv", index_col = 0)
cars_df

        US United States    809  FALSE
USCA
ASPAC  AUS     Australia  731.0   True
ASPAC  JAP         Japan  588.0   True
ASPAC   IN         India   18.0   True
ASPAC   RU        Russia  200.0  False
LATAM  MOR       Morocco   70.0  False
AFR     EG         Egypt   45.0  False
EUR    ENG       England    NaN   True

In [57]:
import pandas as pd
marks = pd.read_csv("marks_1.csv",delimiter = "|", header = None, index_col = 0) 
marks.index.name = "S.No."
marks.columns = ["Name","Subject","Marks","Marks Obtained","Percentage"]
marks

          Name      Subject  Marks  Marks Obtained  Percentage
S.No.
1       Akshay  Mathematics     50              40          80
2       Mahima      English     40              33          83
3        Vikas  Mathematics     50              42          84
4      Abhinav      English     40              31          78
5       Mahima      Science     50              40          80
6       Akshay      Science     50              49          98
7      Abhinav  Mathematics     50              47          94
8        Vikas      Science     50              40          80
9      Abhinav      Science     50              47          94
10       Vikas      English     40              39          98
11      Akshay      English     40              35          88
12      Mahima  Mathematics     50              43          86

In [44]:
#marks_df.header = ["Name", "Subject", "Maximum Marks", "Marks Obtained", "Percentage"]
marks_df.head()

  1|Akshay|Mathematics|50|40|80
0     2|Mahima|English|40|33|83
1  3|Vikas|Mathematics|50|42|84
2    4|Abhinav|English|40|31|78
3     5|Mahima|Science|50|40|80
4     6|Akshay|Science|50|49|98

In [47]:
marks_df = pd.read_csv(del)
marks_df

AttributeError: module 'pandas' has no attribute 'marks_df'