In [6]:
import pandas as pd
pd.read_csv("nba.csv")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import padas as pd
pd.read_csv("day.csv")

ModuleNotFoundError: No module named 'padas'

In [10]:
import pandas as pd 
pd.read_csv("day.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'day.csv'

In [13]:
import pandas as pd 
pd.read_csv("nba.csv")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
import pandas as pd 
df = pd.read_csv("day.csv")
df

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,726,27-12-2019,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
726,727,28-12-2019,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
727,728,29-12-2019,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     730 non-null    int64
 1   dteday      730 non-null    object
 2   season      730 non-null    int64
 3   yr          730 non-null    int64
 4   mnth        730 non-null    int64
 5   holiday     730 non-null    int64
 6   weekday     730 non-null    int64
 7   workingday  730 non-null    int64
 8   weathersit  730 non-null    int64
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64
 14  registered  730 non-null    int64
 15  cnt         730 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.4+ KB

In [22]:
df.shape

(730, 16)

In [23]:
df.tail(2)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
728,729,30-12-2019,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
729,730,31-12-2019,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729

In [27]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [29]:
len(df.columns)

16

In [30]:
df["temp"]

0      14.110847
1      14.902598
2       8.050924
3       8.200000
4       9.305237
         ...
725    10.420847
726    10.386653
727    10.386653
728    10.489153
729     8.849153
Name: temp, Length: 730, dtype: float64

In [31]:
df[["temp","season","mnth"]]

          temp  season  mnth
0    14.110847       1     1
1    14.902598       1     1
2     8.050924       1     1
3     8.200000       1     1
4     9.305237       1     1
..         ...     ...   ...
725  10.420847       1    12
726  10.386653       1    12
727  10.386653       1    12
728  10.489153       1    12
729   8.849153       1    12

[730 rows x 3 columns]

In [32]:
df["season"].unique()

array([1, 2, 3, 4])

In [34]:
df["mnth"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
df["mnth"].count()

730

In [36]:
df["season"].nunique()

4

In [40]:
df["weathersit"].value_counts()

1    463
2    246
3     21
Name: weathersit, dtype: int64

In [ ]:
df["weathersit"].value_counts()

In [43]:
df.nunique()

instant       730
dteday        730
season          4
yr              2
mnth           12
holiday         2
weekday         7
workingday      2
weathersit      3
temp          498
atemp         689
hum           594
windspeed     649
casual        605
registered    678
cnt           695
dtype: int64

In [2]:
df.count()

NameError: name 'df' is not defined

In [45]:
df["weathersit"].value_counts(normalize = True)

1    0.634247
2    0.336986
3    0.028767
Name: weathersit, dtype: float64

In [1]:
df_month = df[df["mnth"]== 2]
df_month.head()

NameError: name 'df' is not defined

In [47]:
df[(df["mnth"]==2) & (df["temp"]>10)]

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
32,33,02-02-2018,1,0,2,0,5,1,2,10.660000,12.72085,77.5417,17.708636,72,1454,1526
36,37,06-02-2018,1,0,2,0,2,1,1,11.719153,14.58355,56.8333,9.500600,354,1269,1623
37,38,07-02-2018,1,0,2,0,3,1,1,11.138347,15.18290,73.8333,3.042356,120,1592,1712
43,44,13-02-2018,1,0,2,0,2,1,1,12.977402,16.20565,45.7391,17.479161,397,1192,1589
44,45,14-02-2018,1,0,2,0,3,1,1,17.015000,19.91750,37.5833,27.999836,208,1705,1913
45,46,15-02-2018,1,0,2,0,4,1,1,10.909567,12.71370,31.4348,19.522058,140,1675,1815
46,47,16-02-2018,1,0,2,0,5,1,1,13.048701,15.81000,42.3478,16.869997,218,1897,2115
47,48,17-02-2018,1,0,2,0,6,0,1,17.869153,21.43290,50.5000,15.416968,259,2216,2475
48,49,18-02-2018,1,0,2,0,0,0,1,21.388347,25.59915,51.6667,17.749975,579,2348,2927
49,50,19-02-2018,1,0,2,0,1,1,1,16.365847,19.57020,18.7917,34.000021,532,1103,1635
50,51,20-02-2018,1,0,2,0,2,1,1,11.693897,13.86650,40.7826,14.956745,639,1173,1812
51,52,21-02-2018,1,0,2,1,3,0,2,12.436653,14.20375,60.5000,20.625682,195,912,1107
54,55,24-02-2018,1,0,2,0,6,0,2,12.121732,14.45955,69.7391,16.783232,100,1707,1807
55,56,25-02-2018,1,0,2,0,0,0,2,14.938268,17.52305,71.2174,23.218113,120,1341,1461
56,57,26-02-2018,1,0,2,0,1,1,1,11.582500,14.10960,53.7917,12.500257,424,1545,1969
57,58,27-02-2018,1,0,2,0,2,1,1,14.082598,17.55545,68.0000,8.391616,694,1708,2402
58,59,28-02-2018,1,0,2,0,3,1,2,16.698193,20.00590,87.6364,19.408962,81,1365,1446
396,397,01-02-2019,1,1,2,0,5,1,1,19.235847,23.32690,50.7917,12.667489,304,4275,4579
397,398,02-02-2019,1,1,2,0,6,0,2,16.365847,19.94855,67.2917,12.541529,190,3571,3761
398,399,03-02-2019,1,1,2,0,0,0,1,12.846653,15.46730,52.6667,11.959232,310,3841,4151
399,400,04-02-2019,1,1,2,0,1,1,2,10.830847,13.63625,77.9583,8.167032,384,2448,2832
400,401,05-02-2019,1,1,2,0,2,1,2,10.899153,13.22605,68.7917,11.791732,318,2629,2947
401,402,06-02-2019,1,1,2,0,3,1,1,11.586969,14.82130,62.2174,10.304600,206,3578,3784
402,403,07-02-2019,1,1,2,0,4,1,1,14.520847,18.05520,49.6250,9.874393,199,4176,4375
403,404,08-02-2019,1,1,2,0,5,1,2,10.523347,13.32105,72.2917,8.959307,109,2693,2802
404,405,09-02-2019,1,1,2,0,6,0,1,10.865000,13.09940,56.2083,13.000479,163,3667,3830
405,406,10-02-2019,1,1,2,0,0,0,2,11.514153,14.67790,54.0000,7.834243,227,3604,3831
409,410,14-02-2019,1,1,2,0,4,1,2,13.085847,16.69730,50.8750,9.458993,135,3787,3922
410,411,15-02-2019,1,1,2,0,5,1,1,14.281653,17.58145,53.1250,12.167200,141,4028,4169
411,412,16-02-2019,1,1,2,0,6,0,2,12.983347,16.50810,75.2917,6.125475,74,2931,3005
412,413,17-02-2019,1,1,2,0,0,0,1,14.076653,17.58145,63.4583,13.791682,349,3805,4154
413,414,18-02-2019,1,1,2,0,1,1,1,14.213347,17.77125,53.4583,12.792243,1435,2883,4318
414,415,19-02-2019,1,1,2,0,2,1,2,11.480000,13.28940,51.5833,16.958504,618,2071,2689
415,416,20-02-2019,1,1,2,1,3,0,1,11.480000,13.66955,50.7826,15.348561,502,2627,3129
416,417,21-02-2019,1,1,2,0,4,1,1,11.800866,14.75565,59.4348,13.783039,163,3614,3777
417,418,22-02-2019,1,1,2,0,5,1,1,16.229153,19.63335,56.7917,15.709557,394,4379,4773
418,419,23-02-2019,1,1,2,0,6,0,1,18.620847,22.22230,55.4583,12.791171,516,4546,5062
419,420,24-02-2019,1,1,2,0,0,0,2,16.707500,20.54855,73.7500,15.916989,246,3241,3487
420,421,25-02-2019,1,1,2,0,1,1,1,11.924153,12.78375,39.5833,28.250014,317,2415,2732
421,422,26-02-2019,1,1,2,0,2,1,1,11.445847,13.41540,41.0000,13.750343,515,2874,3389
422,423,27-02-2019,1,1,2,0,3,1,1,15.033347,17.89770,49.0833,17.958211,253,4069,4322
423,424,28-02-2019,1,1,2,0,4,1,1,14.725847,17.67625,39.5833,12.958939,229,4134,4363

In [50]:
df["temp"].mean()

20.31925921698629

In [51]:
df["temp"].median()

20.4658265

In [52]:
df["temp"].var()

56.35097933285952

In [53]:
df.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.995890,0.690411,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.000339,0.462641,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
25%,183.250000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,13.811885,16.889713,52.000000,9.041650,316.250000,2502.250000,3169.750000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
75%,547.750000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,26.880615,30.445775,72.989575,15.625589,1096.500000,4783.250000,5966.000000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [54]:
df.describe(percentiles = [0.1,0.2,0.3,0.5,])

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000,730.000000
mean,365.500000,2.498630,0.500000,6.526027,0.028767,2.995890,0.690411,1.394521,20.319259,23.726322,62.765175,12.763620,849.249315,3658.757534,4508.006849
std,210.877136,1.110184,0.500343,3.450215,0.167266,2.000339,0.462641,0.544807,7.506729,8.150308,14.237589,5.195841,686.479875,1559.758728,1936.011647
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.424346,3.953480,0.000000,1.500244,2.000000,20.000000,22.000000
10%,73.900000,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.000000,10.653165,12.752280,45.000000,6.704754,139.900000,1506.000000,1742.600000
20%,146.800000,1.000000,0.000000,3.000000,0.000000,1.000000,0.000000,1.000000,12.942322,15.554880,49.975000,8.388467,245.800000,2208.600000,2653.800000
30%,219.700000,2.000000,0.000000,4.000000,0.000000,2.000000,0.000000,1.000000,14.991576,18.204105,54.183310,9.583553,391.000000,2808.700000,3517.000000
50%,365.500000,3.000000,0.500000,7.000000,0.000000,3.000000,1.000000,1.000000,20.465826,24.368225,62.625000,12.125325,717.000000,3664.500000,4548.500000
max,730.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,35.328347,42.044800,97.250000,34.000021,3410.000000,6946.000000,8714.000000

In [55]:
df.sample()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
401,402,06-02-2019,1,1,2,0,3,1,1,11.586969,14.8213,62.2174,10.3046,206,3578,3784

In [56]:
df.sample(3)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
376,377,12-01-2019,1,1,1,0,6,0,2,15.682500,19.09690,80.2917,12.124789,269,3828,4097
518,519,03-06-2019,2,1,6,0,1,1,1,24.702500,28.75665,49.3333,12.333829,2494,5147,7641
417,418,22-02-2019,1,1,2,0,5,1,1,16.229153,19.63335,56.7917,15.709557,394,4379,4773

In [57]:
df.sample(20)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
152,153,02-06-2018,2,0,6,0,6,0,1,29.315000,32.19710,30.5000,19.583229,736,4232,4968
543,544,28-06-2019,3,1,6,0,5,1,1,30.715847,33.77560,42.2500,11.500550,921,5958,6879
318,319,15-11-2018,4,0,11,0,4,1,2,21.730000,25.37895,68.8750,13.375411,449,3746,4195
558,559,13-07-2019,3,1,7,0,6,0,2,29.998347,33.39665,48.5833,5.416950,1511,5988,7499
512,513,28-05-2019,2,1,5,1,2,0,1,29.212500,33.96500,67.6250,13.166907,2557,3486,6043
283,284,11-10-2018,4,0,10,0,4,1,2,23.233347,27.30480,80.8750,9.583814,667,3896,4563
425,426,02-03-2019,1,1,3,0,6,0,2,14.486653,17.99210,65.7083,9.708568,246,2948,3194
293,294,21-10-2018,4,0,10,0,0,0,1,17.527500,21.17980,57.4167,14.833532,676,3628,4304
114,115,25-04-2018,2,0,4,0,3,1,1,24.873347,28.72500,77.6667,12.417311,773,3300,4073
205,206,25-07-2018,3,0,7,0,3,1,1,30.476653,36.04790,75.7083,6.084156,568,3272,3840
489,490,05-05-2019,2,1,5,0,0,0,2,25.488347,29.23040,75.6667,10.250464,2496,4387,6883
215,216,04-08-2018,3,0,8,0,6,0,2,29.110000,33.23940,75.7500,13.209050,799,3777,4576
117,118,28-04-2018,2,0,4,0,6,0,2,25.317500,28.94645,70.0833,21.500836,569,3489,4058
481,482,27-04-2019,2,1,4,0,6,0,1,18.757500,22.63185,40.0833,23.291411,1014,5219,6233
213,214,02-08-2018,3,0,8,0,4,1,1,32.116653,35.35355,49.1250,13.791950,801,4044,4845
235,236,24-08-2018,3,0,8,0,5,1,1,27.606653,31.53460,60.5000,16.958236,949,4181,5130
191,192,11-07-2018,3,0,7,0,3,1,1,31.262500,36.49020,63.5833,18.916579,723,3363,4086
200,201,20-07-2018,3,0,7,0,5,1,1,31.501653,37.34250,70.7083,7.625739,644,3688,4332
501,502,17-05-2019,2,1,5,0,5,1,1,24.326653,28.63065,52.0000,15.374825,1242,6142,7384
664,665,27-10-2019,4,1,10,0,0,0,2,21.730000,25.75665,72.0000,15.791364,2643,5209,7852

In [60]:
sub_df = df.sample(20)

In [61]:
sub_df = sub_df[["temp","hum","mnth","windspeed"]]

In [62]:
sub_df

          temp      hum  mnth  windspeed
706  15.648347  91.1250    12   6.792393
365  15.170000  69.2500     1  12.875189
111  13.803347  72.9583     4  14.707907
287  20.773347  48.3333    10  17.291561
7     6.765000  53.5833     1  17.875868
433  11.787500  35.0417     3  15.125250
593  29.656653  57.0833     8  15.500718
238  27.880000  85.0000     8  25.166339
358  11.266103  68.1304    12  10.391097
21    2.424346  40.0000     1  11.521990
93   23.506653  42.6250     4  25.833257
594  27.811653  60.3333     8  11.917089
610  29.007500  79.0833     9  10.125107
489  25.488347  75.6667     5  10.250464
247  27.606653  79.0417     9  14.250632
133  21.354153  92.2500     5   9.041650
548  32.014153  49.2083     7   8.457879
599  28.529153  63.5833     8   5.667919
485  25.146653  65.9583     5  10.458432
622  24.941653  50.1667     9  16.583907

In [63]:
sub_df.sort_values(by="mnth")

          temp      hum  mnth  windspeed
21    2.424346  40.0000     1  11.521990
365  15.170000  69.2500     1  12.875189
7     6.765000  53.5833     1  17.875868
433  11.787500  35.0417     3  15.125250
111  13.803347  72.9583     4  14.707907
93   23.506653  42.6250     4  25.833257
485  25.146653  65.9583     5  10.458432
133  21.354153  92.2500     5   9.041650
489  25.488347  75.6667     5  10.250464
548  32.014153  49.2083     7   8.457879
599  28.529153  63.5833     8   5.667919
593  29.656653  57.0833     8  15.500718
238  27.880000  85.0000     8  25.166339
594  27.811653  60.3333     8  11.917089
622  24.941653  50.1667     9  16.583907
610  29.007500  79.0833     9  10.125107
247  27.606653  79.0417     9  14.250632
287  20.773347  48.3333    10  17.291561
358  11.266103  68.1304    12  10.391097
706  15.648347  91.1250    12   6.792393

In [64]:
sub_df.sort_values(by=["mnth","temp"])

          temp      hum  mnth  windspeed
21    2.424346  40.0000     1  11.521990
7     6.765000  53.5833     1  17.875868
365  15.170000  69.2500     1  12.875189
433  11.787500  35.0417     3  15.125250
111  13.803347  72.9583     4  14.707907
93   23.506653  42.6250     4  25.833257
133  21.354153  92.2500     5   9.041650
485  25.146653  65.9583     5  10.458432
489  25.488347  75.6667     5  10.250464
548  32.014153  49.2083     7   8.457879
594  27.811653  60.3333     8  11.917089
238  27.880000  85.0000     8  25.166339
599  28.529153  63.5833     8   5.667919
593  29.656653  57.0833     8  15.500718
622  24.941653  50.1667     9  16.583907
247  27.606653  79.0417     9  14.250632
610  29.007500  79.0833     9  10.125107
287  20.773347  48.3333    10  17.291561
358  11.266103  68.1304    12  10.391097
706  15.648347  91.1250    12   6.792393

In [65]:
sub_df.sort_values(by=["mnth","temp"],ascending = False)

          temp      hum  mnth  windspeed
706  15.648347  91.1250    12   6.792393
358  11.266103  68.1304    12  10.391097
287  20.773347  48.3333    10  17.291561
610  29.007500  79.0833     9  10.125107
247  27.606653  79.0417     9  14.250632
622  24.941653  50.1667     9  16.583907
593  29.656653  57.0833     8  15.500718
599  28.529153  63.5833     8   5.667919
238  27.880000  85.0000     8  25.166339
594  27.811653  60.3333     8  11.917089
548  32.014153  49.2083     7   8.457879
489  25.488347  75.6667     5  10.250464
485  25.146653  65.9583     5  10.458432
133  21.354153  92.2500     5   9.041650
93   23.506653  42.6250     4  25.833257
111  13.803347  72.9583     4  14.707907
433  11.787500  35.0417     3  15.125250
365  15.170000  69.2500     1  12.875189
7     6.765000  53.5833     1  17.875868
21    2.424346  40.0000     1  11.521990

In [67]:
sub_df.sort_values(by=["mnth","temp"],ascending = [False, True])

          temp      hum  mnth  windspeed
358  11.266103  68.1304    12  10.391097
706  15.648347  91.1250    12   6.792393
287  20.773347  48.3333    10  17.291561
622  24.941653  50.1667     9  16.583907
247  27.606653  79.0417     9  14.250632
610  29.007500  79.0833     9  10.125107
594  27.811653  60.3333     8  11.917089
238  27.880000  85.0000     8  25.166339
599  28.529153  63.5833     8   5.667919
593  29.656653  57.0833     8  15.500718
548  32.014153  49.2083     7   8.457879
133  21.354153  92.2500     5   9.041650
485  25.146653  65.9583     5  10.458432
489  25.488347  75.6667     5  10.250464
111  13.803347  72.9583     4  14.707907
93   23.506653  42.6250     4  25.833257
433  11.787500  35.0417     3  15.125250
21    2.424346  40.0000     1  11.521990
7     6.765000  53.5833     1  17.875868
365  15.170000  69.2500     1  12.875189

In [ ]:
#Groupby

In [68]:
df.groupby("mnth")["temp"].mean()

mnth
1      9.694201
2     12.235249
3     16.012089
4     19.269952
5     24.386735
6     28.047985
7     30.974287
8     29.051844
9     25.275884
10    19.885500
11    15.138010
12    13.285270
Name: temp, dtype: float64

In [69]:
df.groupby("mnth")["temp"].max()

mnth
1     17.425000
2     21.388347
3     24.668347
4     27.230847
5     31.775000
6     34.200847
7     35.328347
8     32.526653
9     30.886653
10    26.957500
11    21.730000
12    19.509153
Name: temp, dtype: float64

In [70]:
df.groupby("mnth")[["temp","windspeed"]].max()

           temp  windspeed
mnth
1     17.425000  27.833743
2     21.388347  34.000021
3     24.668347  29.584721
4     27.230847  26.000489
5     31.775000  22.958689
6     34.200847  23.292014
7     35.328347  19.082471
8     32.526653  25.166339
9     30.886653  23.958329
10    26.957500  28.292425
11    21.730000  25.250357
12    19.509153  27.292182

In [72]:
df.groupby("mnth").agg({"temp":["mean","median"],"windspeed":["var","std","count"],"hum":["mean"]})

           temp             windspeed                        hum
           mean     median        var       std count       mean
mnth
1      9.694201   8.917500  28.764151  5.363222    62  58.582827
2     12.235249  11.706525  37.673216  6.137851    56  56.322686
3     16.012089  15.594124  27.284481  5.223455    62  58.847503
4     19.269952  18.842923  26.756566  5.172675    60  58.806312
5     24.386735  24.429153  17.838637  4.223581    62  68.895831
6     28.047985  28.307077  16.804018  4.099270    60  57.580552
7     30.974287  30.698750   8.590651  2.930981    62  59.787632
8     29.051844  29.015536  18.590783  4.311703    62  63.773010
9     25.275884  25.471250  19.755662  4.444734    60  71.471437
10    19.885500  20.124173  33.708793  5.805927    62  69.376087
11    15.138010  14.725847  32.654091  5.714376    60  62.487648
12    13.285270  12.846673  34.586894  5.881062    62  66.604052

In [73]:
df.groupby(["yr","mnth"]).agg({"temp":["mean","median"],"windspeed":["var","std","count"],"hum":["mean"]})

              temp             windspeed                        hum
              mean     median        var       std count       mean
yr mnth
0  1      8.105974   8.057402  24.460422  4.945748    31  58.436635
   2     11.584143  11.360423  50.078154  7.076592    28  56.009311
   3     13.598330  13.013031  13.275713  3.643585    31  56.941384
   4     19.318726  18.842923  24.677209  4.967616    30  66.828740
   5     23.666480  22.550000  20.396291  4.516225    31  71.336019
   6     28.416417  28.529173  14.742197  3.839557    30  59.324997
   7     31.101588  30.647500  10.573404  3.251677    31  58.966397
   8     28.919847  28.989419  18.394443  4.288874    31  62.683113
   9     25.128349  25.995640  16.068310  4.008530    30  78.405377
   10    19.268996  19.850847  37.871899  6.154015    31  70.679468
   11    16.495863  16.417077  31.313479  5.595845    30  67.530970
   12    13.332471  12.812500  28.017965  5.293200    31  64.918300
1  1     11.282428  11.240847  32.927693  5.738266    31  58.729019
   2     12.886354  12.385403  25.270724  5.026999    28  56.636061
   3     18.425848  19.133347  41.328332  6.428712    31  60.753623
   4     19.221179  18.894153  28.878528  5.373875    30  50.783883
   5     25.106990  25.112500  15.848330  3.980996    31  66.455642
   6     27.679554  26.855000  18.960532  4.354369    30  55.836107
   7     30.846986  30.784153   6.602427  2.569519    31  60.608868
   8     29.183841  29.349153  16.466616  4.057908    31  64.862906
   9     25.423418  25.061250  22.565317  4.750297    30  64.537497
   10    20.502004  21.080847  30.667176  5.537795    31  68.072706
   11    13.780157  13.991250  35.044971  5.919879    30  57.444327
   12    13.238068  13.154153  41.627525  6.451940    31  68.289803

In [75]:
df = df.rename(columns = {"mnth": "month","temp": "temperature"})

In [76]:
df.head()

,instant,dteday,season,yr,month,holiday,weekday,workingday,weathersit,temperature,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [78]:
df.set_index("dteday")

,instant,season,yr,month,holiday,weekday,workingday,weathersit,temperature,atemp,hum,windspeed,casual,registered,cnt
dteday,,,,,,,,,,,,,,,
01-01-2018,1,1,0,1,0,1,1,2,14.110847,18.18125,80.5833,10.749882,331,654,985
02-01-2018,2,1,0,1,0,2,1,2,14.902598,17.68695,69.6087,16.652113,131,670,801
03-01-2018,3,1,0,1,0,3,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
04-01-2018,4,1,0,1,0,4,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
05-01-2018,5,1,0,1,0,5,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27-12-2019,726,1,1,12,0,5,1,2,10.420847,11.33210,65.2917,23.458911,247,1867,2114
28-12-2019,727,1,1,12,0,6,0,2,10.386653,12.75230,59.0000,10.416557,644,2451,3095
29-12-2019,728,1,1,12,0,0,0,2,10.386653,12.12000,75.2917,8.333661,159,1182,1341
30-12-2019,729,1,1,12,0,1,1,1,10.489153,11.58500,48.3333,23.500518,364,1432,1796
31-12-2019,730,1,1,12,0,2,1,2,8.849153,11.17435,57.7500,10.374682,439,2290,2729