In [5]:
import pandas as pd 
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
mycols = ["Name", "College"]
nba[mycols].head()

            Name            College
0  Avery Bradley              Texas
1    Jae Crowder          Marquette
2   John Holland  Boston University
3    R.J. Hunter      Georgia State
4  Jonas Jerebko                NaN

In [7]:
#filtering records

In [8]:
#find te players plying texas college

In [10]:
texasPlayers = nba.College == "Texas"
nba[texasPlayers]

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

In [12]:
texasPlayers = nba.Team == 'Toronto Raptors' 
nba[texasPlayers]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
61,Bismack Biyombo,Toronto Raptors,8.0,C,23.0,6-9,245.0,False,2814000.0
62,Bruno Caboclo,Toronto Raptors,20.0,SF,20.0,6-9,205.0,False,1524000.0
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,6-8,212.0,False,13600000.0
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,6-7,220.0,False,10050000.0
65,James Johnson,Toronto Raptors,3.0,PF,29.0,6-9,250.0,False,2500000.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,True,7000000.0
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,False,12000000.0
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,False,1842000.0
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,6-9,235.0,False,6268675.0
70,Norman Powell,Toronto Raptors,24.0,SG,23.0,6-4,215.0,False,650000.0
71,Terrence Ross,Toronto Raptors,31.0,SF,25.0,6-7,195.0,False,3553917.0
72,Luis Scola,Toronto Raptors,4.0,PF,36.0,6-9,240.0,False,2900000.0
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,False,245177.0
74,Jonas Valanciunas,Toronto Raptors,17.0,C,24.0,7-0,255.0,False,4660482.0
75,Delon Wright,Toronto Raptors,55.0,PG,24.0,6-5,190.0,False,1509360.0

In [16]:
#find players from "Texas" College Playing for "PG" Position 
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,True,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,False,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,False,NaN

In [17]:
c1 = nba.College == "Texas"
c2 = nba.Position == "PG"
nba[c1 & c2]

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

In [18]:
c1 = nba.Age == 22 
c2 = nba.Weight >= 253 
nba[ c1 & c2 ]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,False,3807120.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,False,3272091.0
412,Steven Adams,Oklahoma City Thunder,12.0,C,22.0,7-0,255.0,False,2279040.0

In [19]:
#Dealing wiht Nan in pandas

In [20]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,True,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,False,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,False,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,False,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,False,5000000.0

In [ ]:
#delting the rows with all the value with

In [22]:
nba = pd.read_csv("nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [24]:
round(nba.Salary.mean(),2)

4842684.11

In [26]:
nba.Salary.fillna(round(nba.Salary.mean(),2) , inplace = True)

In [27]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.00
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.00
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4842684.11
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.00
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.00

In [ ]:
nba.Salary.fillna(round(nba.College.mean(),2) , inplace = True)

In [29]:
nba.College.fillna("Others", inplace= True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.00
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.00
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,4842684.11
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.00
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Others,5000000.00

In [ ]:
#data type conversion in padas

In [31]:
import pandas as pd
df = pd.read_csv("employees.csv")
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [32]:
df.dtypes

First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object

In [33]:
df["Start Date"] = pd.to_datetime(df["Start Date"])

In [34]:
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time              object
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [36]:
df['Last Login Time']= pd.to_datetime(df['Last Login Time'])
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time      datetime64[ns]
Salary                        int64
Bonus %                     float64
Senior Management            object
Team                         object
dtype: object

In [38]:
df["Senior Management"] = df["Senior Management"].astype("bool")

In [39]:
df.dtypes

First Name                   object
Gender                       object
Start Date           datetime64[ns]
Last Login Time      datetime64[ns]
Salary                        int64
Bonus %                     float64
Senior Management              bool
Team                         object
dtype: object

In [40]:
#analytical function in padas

In [41]:
df.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2023-01-29 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2023-01-29 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2023-01-29 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2023-01-29 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2023-01-29 16:47:00,101004,1.389,True,Client Services

In [42]:
df.Gender.nunique()

2

In [ ]:
#how many

In [45]:
df.Team.nunique()

10

In [46]:
df.Gender.unique()

array(['Male', 'Female', nan], dtype=object)

In [49]:
df.Team.unique()

array(['Marketing', nan, 'Finance', 'Client Services', 'Legal', 'Product',
       'Engineering', 'Business Development', 'Human Resources', 'Sales',
       'Distribution'], dtype=object)

In [50]:
#How many males & females their??
# unique shows vallue what are present & count shows no of time values are present
df.Gender.value_counts()

Female    431
Male      424
Name: Gender, dtype: int64

In [51]:
df.Team.value_counts()

Client Services         106
Finance                 102
Business Development    101
Marketing                98
Product                  95
Sales                    94
Engineering              92
Human Resources          91
Distribution             90
Legal                    88
Name: Team, dtype: int64

In [54]:
#how many males & feamsle are working in Finance team???

In [55]:
finEmp = df.Team == "Finance"
finTeam = df[finEmp]
finTeam.Gender.value_counts()

Female    44
Male      41
Name: Gender, dtype: int64

In [58]:
#who is the most pad employee
hp = df.Salary == 
hp

0       97308
1       61933
2      130590
3      138705
4      101004
        ...
995    132483
996     42392
997     96914
998     60500
999    129949
Name: Salary, Length: 1000, dtype: int64

In [59]:
Marketing = df.Team == "Marketing" 
SM = df["Senior Management"] == True 
newdf = df[Marketing & SM] 
newdf.sort_values (by = "Salary")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
331,Evelyn,Female,1983-09-03,2023-01-29 13:58:00,36759,17.269,True,Marketing
894,Betty,Female,2002-11-19,2023-01-29 10:40:00,37005,7.645,True,Marketing
26,Craig,Male,2000-02-27,2023-01-29 07:45:00,37598,7.757,True,Marketing
168,Peter,NaN,1987-09-03,2023-01-29 17:59:00,38989,7.017,True,Marketing
617,Kathy,Female,2001-01-14,2023-01-29 05:11:00,45682,1.451,True,Marketing
601,Christine,NaN,1980-06-15,2023-01-29 18:00:00,50366,9.862,True,Marketing
659,Steve,NaN,2009-08-27,2023-01-29 15:41:00,53692,4.785,True,Marketing
204,Willie,Male,2006-06-06,2023-01-29 09:45:00,55281,4.935,True,Marketing
785,NaN,Female,1982-07-24,2023-01-29 00:00:00,57811,8.941,True,Marketing
62,NaN,Female,2007-06-12,2023-01-29 17:25:00,58112,19.414,True,Marketing
271,Frank,NaN,2001-11-20,2023-01-29 10:18:00,58563,12.062,True,Marketing
327,Aaron,Male,1994-01-29,2023-01-29 18:48:00,58755,5.097,True,Marketing
101,Aaron,Male,2012-02-17,2023-01-29 10:20:00,61602,11.849,True,Marketing
400,Billy,NaN,2004-03-16,2023-01-29 08:21:00,62913,18.241,True,Marketing
353,NaN,Male,1997-04-22,2023-01-29 21:36:00,65078,3.095,True,Marketing
730,Nicole,Female,2009-04-26,2023-01-29 00:40:00,66047,18.674,True,Marketing
556,Arthur,Male,2014-12-16,2023-01-29 16:56:00,66819,6.639,True,Marketing
446,Cheryl,Female,1994-08-16,2023-01-29 08:33:00,67150,15.850,True,Marketing
252,Ralph,Male,2004-11-11,2023-01-29 01:35:00,71896,4.232,True,Marketing
220,NaN,Female,1991-06-17,2023-01-29 12:49:00,71945,5.560,True,Marketing
43,Marilyn,Female,1980-12-07,2023-01-29 03:16:00,73524,5.207,True,Marketing
942,Lori,Female,2015-11-20,2023-01-29 13:15:00,75498,6.537,True,Marketing
496,Johnny,Male,2016-02-26,2023-01-29 19:39:00,76394,5.437,True,Marketing
625,Cynthia,Female,2015-06-29,2023-01-29 06:38:00,82408,8.701,True,Marketing
550,Gregory,Male,1984-06-18,2023-01-29 03:46:00,82726,16.304,True,Marketing
930,Nancy,Female,2001-09-10,2023-01-29 23:57:00,85213,2.386,True,Marketing
696,Samuel,Male,2012-05-25,2023-01-29 16:40:00,85550,11.593,True,Marketing
722,Joshua,Male,1997-06-27,2023-01-29 15:23:00,95003,5.197,True,Marketing
0,Douglas,Male,1993-08-06,2023-01-29 12:42:00,97308,6.945,True,Marketing
274,Howard,Male,1982-10-05,2023-01-29 07:22:00,97490,5.460,True,Marketing
994,George,Male,2013-06-21,2023-01-29 17:47:00,98874,4.479,True,Marketing
98,Tina,Female,2016-06-16,2023-01-29 19:47:00,100705,16.961,True,Marketing
798,Lawrence,Male,1984-10-01,2023-01-29 14:06:00,102589,17.952,True,Marketing
667,Douglas,NaN,2009-02-04,2023-01-29 02:03:00,104496,14.771,True,Marketing
544,Roger,Male,2010-07-03,2023-01-29 17:11:00,105689,13.320,True,Marketing
947,NaN,Male,2012-07-30,2023-01-29 15:07:00,107351,5.329,True,Marketing
77,Charles,Male,2004-09-14,2023-01-29 20:13:00,107391,1.260,True,Marketing
656,Lisa,Female,1982-02-09,2023-01-29 18:44:00,113592,17.108,True,Marketing
158,Norma,Female,1999-02-28,2023-01-29 20:45:00,114412,8.756,True,Marketing
413,Johnny,Male,1992-09-14,2023-01-29 08:21:00,115194,5.861,True,Marketing
379,NaN,Female,2002-09-18,2023-01-29 12:39:00,118906,4.537,True,Marketing
813,Evelyn,Female,2002-02-10,2023-01-29 04:44:00,123621,19.767,True,Marketing
531,Virginia,Female,2010-05-02,2023-01-29 21:10:00,123649,10.154,True,Marketing
503,Roger,Male,2015-08-03,2023-01-29 16:56:00,125033,4.887,True,Marketing
811,Judith,Female,1989-09-03,2023-01-29 11:16:00,134048,6.818,True,Marketing
991,Rose,Female,2002-08-25,2023-01-29 05:12:00,134505,11.051,True,Marketing
468,Janice,Female,1997-06-28,2023-01-29 13:48:00,136032,10.696,True,Marketing
454,NaN,Male,1995-02-21,2023-01-29 00:26:00,136602,10.429,True,Marketing
459,Charles,NaN,1987-03-01,2023-01-29 13:00:00,137171,5.574,True,Marketing
298,Patrick,NaN,2004-08-30,2023-01-29 11:43:00,137314,4.542,True,Marketing
676,Annie,Female,1992-06-06,2023-01-29 10:04:00,138925,9.801,True,Marketing
451,Terry,NaN,2016-07-15,2023-01-29 00:29:00,140002,19.490,True,Marketing
97,Laura,NaN,2014-07-19,2023-01-29 21:23:00,140371,10.620,True,Marketing
769,Samuel,NaN,2002-10-07,2023-01-29 03:08:00,141305,9.849,True,Marketing
899,Walter,Male,1992-05-21,2023-01-29 00:39:00,144701,16.323,True,Marketing
452,Scott,Male,2012-11-17,2023-01-29 14:47:00,146812,1.965,True,Marketing

In [60]:
import pandas as pd
bond = pd.read_csv("jamesbond.csv")
bond

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
6,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
8,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
9,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
10,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
11,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
12,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
16,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
17,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
18,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
19,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
20,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
21,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
22,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [61]:
#access rows using row indexes 
bond.iloc[2]

Film                   Goldfinger
Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: 2, dtype: object

In [64]:
bond.iloc[[2,5,7]]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
5,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4
7,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8

In [65]:
bond.iloc[:3]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [66]:
bond.iloc[23:]

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
23,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
24,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
25,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN

In [67]:
bond.head(3)

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [69]:
bond.set_index("Film",inplace = True)

In [70]:
bond.head(3)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [71]:
#when we are using index other then row index use .loc

SyntaxError: invalid syntax (1768953886.py, line 1)

In [73]:
bond.loc["Goldfinger"]

Year                         1964
Actor                Sean Connery
Director             Guy Hamilton
Box Office                  820.4
Budget                       18.6
Bond Actor Salary             3.2
Name: Goldfinger, dtype: object

In [74]:
bond.reset_index(inplace = True)

In [75]:
bond.head()

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
1,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
2,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
3,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
4,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN

In [77]:
bond.set_index("Year",inplace = True)
bond.head()

,Film,Actor,Director,Box Office,Budget,Bond Actor Salary
Year,,,,,,
1962,Dr. No,Sean Connery,Terence Young,448.8,7.0,0.6
1963,From Russia with Love,Sean Connery,Terence Young,543.8,12.6,1.6
1964,Goldfinger,Sean Connery,Guy Hamilton,820.4,18.6,3.2
1965,Thunderball,Sean Connery,Terence Young,848.1,41.9,4.7
1967,Casino Royale,David Niven,Ken Hughes,315.0,85.0,NaN

In [82]:
bond.loc[1985]

Film                 A View to a Kill
Actor                     Roger Moore
Director                    John Glen
Box Office                      275.2
Budget                           54.5
Bond Actor Salary                 9.1
Name: 1985, dtype: object

In [83]:
bond.reset_index(inplace = True)

In [84]:
fortune = pd.read_csv("fortune1000.csv", index_col = "Rank") 
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [87]:
fortune.shape

(1000, 7)

In [88]:
fortune.Sector.nunique()

21

In [92]:
fortune.Sector.value_counts()

Financials                      139
Energy                          122
Technology                      102
Retailing                        80
Health Care                      75
Business Services                51
Industrials                      46
Materials                        43
Food, Beverages & Tobacco        43
Wholesalers                      40
Transportation                   36
Chemicals                        30
Household Products               28
Engineering & Construction       26
Media                            25
Hotels, Resturants & Leisure     25
Motor Vehicles & Parts           24
Aerospace & Defense              20
Telecommunications               15
Apparel                          15
Food and Drug Stores             15
Name: Sector, dtype: int64

In [93]:
#Points to note
#There are 21 Groups(data frames ) inside secgrp objects 
#each group is named after

In [98]:
secGrp = fortune.groupby("Sector")

In [104]:
secGrp.get_group('Technology')['Profits'].sum()

180473

In [105]:
secGrp.agg({"Revenue": "sum"})

                              Revenue
Sector
Aerospace & Defense            357940
Apparel                         95968
Business Services              272195
Chemicals                      243897
Energy                        1517809
Engineering & Construction     153983
Financials                    2217159
Food and Drug Stores           483769
Food, Beverages & Tobacco      555967
Health Care                   1614707
Hotels, Resturants & Leisure   169546
Household Products             234737
Industrials                    497581
Materials                      259145
Media                          220764
Motor Vehicles & Parts         482540
Retailing                     1465076
Technology                    1377600
Telecommunications             461834
Transportation                 408508
Wholesalers                    444800

In [106]:
secGrp.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000