In [6]:
import pandas as pd 
weather_df = pd.read_csv("weatherdata.csv", header = 0)
weather_df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [8]:
weather_df.shape

(142193, 9)

In [9]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142193 entries, 0 to 142192
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           142193 non-null  object
 1   Location       142193 non-null  object
 2   MinTemp        141556 non-null  float64
 3   MaxTemp        141871 non-null  float64
 4   Rainfall       140787 non-null  float64
 5   Evaporation    81350 non-null   float64
 6   Sunshine       74377 non-null   float64
 7   WindGustDir    132863 non-null  object
 8   WindGustSpeed  132923 non-null  float64
dtypes: float64(6), object(3)
memory usage: 9.8+ MB

In [11]:
weather_df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed
count,141556.000000,141871.000000,140787.000000,81350.000000,74377.000000,132923.000000
mean,12.186400,23.226784,2.349974,5.469824,7.624853,39.984292
std,6.403283,7.117618,8.465173,4.188537,3.781525,13.588801
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000
25%,7.600000,17.900000,0.000000,2.600000,4.900000,31.000000
50%,12.000000,22.600000,0.000000,4.800000,8.500000,39.000000
75%,16.800000,28.200000,0.800000,7.400000,10.600000,48.000000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000

In [12]:
#Find the days which had sunshine for more that 4 hours. These days will have increased sales of sunscreen.

In [13]:
weather_df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0

In [14]:
weather_df["Sunshine"] > 4

0         False
1         False
2         False
3         False
4         False
          ...
142188    False
142189    False
142190    False
142191    False
142192    False
Name: Sunshine, Length: 142193, dtype: bool

In [16]:
sunshine_count = weather_df[weather_df["Sunshine"]>4]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5940,2009-01-02,Cobar,18.4,28.9,0.0,14.8,13.0,S,37.0
5941,2009-01-03,Cobar,15.5,34.1,0.0,12.6,13.3,SE,30.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
...,...,...,...,...,...,...,...,...,...
139108,2017-06-20,Darwin,19.3,33.4,0.0,6.0,11.0,ENE,35.0
139109,2017-06-21,Darwin,21.2,32.6,0.0,7.6,8.6,E,37.0
139110,2017-06-22,Darwin,20.7,32.8,0.0,5.6,11.0,E,33.0
139111,2017-06-23,Darwin,19.5,31.8,0.0,6.2,10.6,ESE,26.0
139112,2017-06-24,Darwin,20.2,31.7,0.0,5.6,10.7,ENE,30.0

In [18]:
weather_df[(weather_df["MaxTemp"]>35) & (weather_df["Sunshine"]>6)]

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
5939,2009-01-01,Cobar,17.9,35.2,0.0,12.0,12.3,SSW,48.0
5942,2009-01-04,Cobar,19.4,37.6,0.0,10.8,10.6,NNE,46.0
5943,2009-01-05,Cobar,21.9,38.4,0.0,11.4,12.2,WNW,31.0
5944,2009-01-06,Cobar,24.2,41.0,0.0,11.2,8.4,WNW,35.0
5948,2009-01-10,Cobar,19.0,35.5,0.0,12.0,12.3,ENE,48.0
...,...,...,...,...,...,...,...,...,...
138862,2016-10-17,Darwin,25.1,35.2,0.0,7.4,11.5,NNE,39.0
138879,2016-11-03,Darwin,24.4,35.5,0.0,7.8,9.9,NW,35.0
138892,2016-11-16,Darwin,25.7,35.2,0.0,5.4,11.3,NW,26.0
138905,2016-11-29,Darwin,25.8,35.1,0.8,4.8,6.4,SSE,46.0
138910,2016-12-04,Darwin,25.8,35.2,0.0,NaN,12.0,ESE,33.0

In [19]:
weather_df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0