In [6]:
print([i for i in range(1,10)])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
import random

In [10]:
jackpot = random.randint(1,100)
guess = int(input("Please guess the number: ")) 
counter = 1
while guess != jackpot: 
    if guess < jackpot: 
        print("Guess Higher")
    else: 
        print("Gues Lower") 

    guess = int(input("Chal guess kar")) 
    counter += 1

print("Right Guess!") 
print("You took", counter, "attempts")

Please guess the number:  50

Guess Higher

Chal guess kar 60

Guess Higher

Chal guess kar 70

Gues Lower

Chal guess kar 65

Gues Lower

Chal guess kar 62

Guess Higher

Chal guess kar 63

Guess Higher

Chal guess kar 64

Right Guess!
You took 7 attempts

In [13]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
for i in range(1,11): 
    print(i)

1
2
3
4
5
6
7
8
9
10

In [15]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [16]:
list(range(1,10,3))

[1, 4, 7]

In [18]:
list(range(10,0,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [22]:
for i in range(1,10): 
    print(i)

1
2
3
4
5
6
7
8
9

In [26]:
rows = int(input("Enter the number of rows")) 

for i in range(1, rows + 1): 
    for j in range(0,i): 
        print("#", end = " ") 
    print("")

Enter the number of rows 10

#
# #
# # #
# # # #
# # # # #
# # # # # #
# # # # # # #
# # # # # # # #
# # # # # # # # #
# # # # # # # # # #

In [27]:
rows = int(input("Enter a number: " )) 
for i in range(1,rows + 1): 
    for j in range(0,i): 
        print("*", end = " ") 
    print("")

Enter a number:  10

*
* *
* * *
* * * *
* * * * *
* * * * * *
* * * * * * *
* * * * * * * *
* * * * * * * * *
* * * * * * * * * *

In [28]:
for i in range(1,10):
    if i == 5: 
        break
    print(i)

1
2
3
4

In [31]:
for i in range(1,10): 
    if i == 5: 
        continue 
    print(i)

1
2
3
4
6
7
8
9

In [33]:
# absolute function 
abs(-5)

5

In [34]:
#power function 
pow(2,3)

8

In [35]:
#min/max 
min([2,3,5,7])

2

In [36]:
max([5,2,8,10])

10

In [37]:
min("Kolkata")

'K'

In [38]:
max("Kolkata")

't'

In [40]:
round(200.9838,2)

200.98

In [43]:
import pandas as pd

In [50]:
df = pd.DataFrame({"Name": ['Robert', 'johny', 'David'], "age": [22,36,23]})
df.head()

     Name  age
0  Robert   22
1   johny   36
2   David   23

In [51]:
df['age'] = df['age'].apply(lambda x: x+5)

In [52]:
df.head()

     Name  age
0  Robert   27
1   johny   41
2   David   28

In [53]:
grouped_df = df.groupby('age').filter(lambda x: x['age'] > 27)
grouped_df

    Name  age
1  johny   41
2  David   28